### ISSUE TITLE
Weird behavior of the scroll-bar appearing when opening the right control panel

### ISSUE THREAD

**Issue by MisterDA** [jech/galene#108]
When opening the right control panel, a scroll-bar appears right of it to allow to discover all the switches.
It appears even if the window's height is important enough to contain all the elements. Maybe the scroll-bar could be hidden in that case? For now, the behavior is just that the browser will disable the slider.
Also, the "logout" button isn't well positioned w.r.t that scroll-bar. Often, it is just hidden behind it.

<img width="199" alt="galene" src="https://user-images.githubusercontent.com/1773581/133801377-46e10acd-de8b-4abe-9681-ba549c9f955b.PNG">

My CSS-fu is really bad, I'll just cc- @takdj ;) if you have an idea.

**Comment by UnSeulT** [comment]
To avoid scrollbar if not necessary :
In galene.css, change [line 995](https://github.com/jech/galene/blob/09c5ba0d0620eb96f2b9edc3525dbaa349e3274e/static/galene.css#L995) to :
`overflow-y: auto;`

To fix the "logout" button under the scrollbar: 
in galene.css, remove the rule starting at [line 51](https://github.com/jech/galene/blob/09c5ba0d0620eb96f2b9edc3525dbaa349e3274e/static/galene.css#L51) :
```
.profile {
    width: 230px;
}
```

**Comment by jech** [comment]
Closed in 7aefb5e9699eaa83111b0a8f49aa249e69541db8
