### ISSUE TITLE
Works with car via Bluetooth 

### ISSUE THREAD

**Issue by gedw99** [jech/galene#113]
I was in my car testing this and was amazed that when using the app it would stop the car radio and switch to the Bluetooth call from the app.

It’s using the Bluetooth connection between my iOS device and the car.

was kind of not expecting that

**Comment by gedw99** [comment]
After done testing it seems very robust.

the audio works.

so you can start a session on your mobile in the car and then go hands free .

**Comment by jech** [comment]
Excellent!
