### ISSUE TITLE
Authentication and authorisation

### ISSUE THREAD

**Issue by jech** [jech/galene#12]
The current authentication and authorisation scheme is simple and expressive, but has some limitations:

  * if a user is authorised in multiple groups, their password entry needs to be duplicated (there is no global password file);
  * there is no means of authentication delegation ("login with Github").

On the latter point, one must carefully distinguish between authentication and authorisation.  Protocols such as OAuth2 delegate *authentication* — they say e.g. that a user has authentic Github credentials, but they say nothing about whether said user is allowed to access a given instance of Galène.

Please refrain from commenting about how horrible OAuth2 is.  This is true, but quite besides the point.

**Comment by ofrzeta** [comment]
You could use JWT for authorization with OpenID Connect or through other means. The token can contain the group membership or other roles you need.

**Comment by athoune** [comment]
You can use JWT token as indirection. In the token, you have one user and one or more groups.

Token creation CAN be done with OAuth2+OpenID, or other way (LDAP, flat file…)

**Comment by athoune** [comment]
## Authentication

Authentication should be done at HTTP level, with headers, not websocket level.

With authenticated users, at website scale, not roomscale, it will be easier to implement authorisations, like one account for multiple room, or, mor fun, some SSO.

Websocket is a HTTP upgrading, when establishing the connection, HTTP header can be read, and a user can attached to the session. With user attached to a websocket, you don't have to explicit name with each chat message.

## Room invitation

Account can be boring, room invitation, with a signed URL, can be the simplest way to handle private rooms. Signed URL can send with some chat application (irc, mattermost, xmpp, whatever…) or plain old mail. Signature has a "not before" and "not after", and user clicking the link is asking for a name/pseudo before joining the room.

**Comment by jech** [comment]
> Authentication should be done at HTTP level, with headers, not websocket level.

Please explain why you think so.  Recall that a user might have different permissions in different groups, and that a single Websocket connection might move from group to group.

> a signed URL

That's not going to happen — it must be possible to bookmark a URL.

**Comment by athoune** [comment]
1) you are authenticated, you have a name and groups, it's in a cookie : you have a http session
2) a room is created, with users and groups, or free for all authenicated users
3) I can go to a page wich display available rooms and if I can enter
4) When I enter in a room, a websocket is created, and the server end of the socket got the content of my cookie

IMHO, it's better to keep multiple pages. Single Page Application is hard, and you have to use React or Vue.
Action are defined with clean REST API, the frontend just use this API, with [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

>> a signed URL

> That's not going to happen — it must be possible to bookmark a URL.

A signed URL is volatil, it must answer 303 with a `Location` header, redirecting to the room.

Invitation is the simplest way to get someone quickly in a chat room.

**Comment by athoune** [comment]
Take the problem upside down, with user stories, with Alice, Bob and Charly.

## Actual Galene behavior

Alice is admin, she edit the json file to create a room, an account for Bob, Charly and herself, and send login+password via a secure channel (mail+gpg, signal, whatever…)

## Something with OAuth

Alice, Bob and Charly have an account in a service handling OAUth2+OpenID.
Alice create a room, with some of this rules :
 * A group
 * A domain for email
 * A list of users

Alice uses some chat service to warn Bob and Charly, and give an URL to the room. All users authenticated with the service and passing rules cans enter to the chat room.

## Something without authentication

Alice has an account on the Galene service. She creates a room. As admin, she can creates signed URL with room, user, not before, not after informations. She send signed url with some chat service, Bob click the url, he is redirected to the room URL, with a cookie. You can set username in the invitation link, or just one universel link for the room, and user set is name before joining the room.

**Comment by georgesk** [comment]
# Using an OpenLDAP directory
Hello, I forked galene and managed to authenticate teachers and students of my school against an OpenLDAP service.
The diff is not that big.

Here are a few fields which can be added to JSON group definitions, to define more precisely how users can join the chat room.
```
{
    "description" : "Salon de démonstration numéro 1",
    "op": [{"username": "demo", "password": "123456"}],
    "presenter": [],
    "ldapurl": "ldap://localhost:1389/dc=lycee,dc=jb",
    "op_ldap": ["^memberOf: CN=profs,"],
    "presenter_ldap": ["^memberOf: CN=profs,"]
}
```
The value `ldap://localhost:1389/dc=lycee,dc=jb` is telling that the LDAP service is provided by localhost, port 1389, and has a base "dc=lycee,dc=jb".

The main idea is to express the roles of a user in a group by a few regexp filters, to be applied on this user's LDAP record.

Would you like to review this code?

Thank you.

**Comment by jech** [comment]
Excellent.  Yes, I'd like to look at the code (but please don't be offended if I don't merge it as is, regexps make me nervous, especially in a security context).

**Comment by georgesk** [comment]
Thank you for your very fast response, Jech!

I shall propose my diff as a pull request; however, I would like you just review the code, and provide me some hints to make it better: I began to learn Go yesterday, so I am not that proficient.

Here are two questions which I asked myself, and I do not believe that I know their best solutions:

1. if we are using LDAP services, Galène has no reason to keep user credentials in any group file: so, **Galène must keep the username and the password** as they were given at first authentication, to reuse them later in other contexts. This was already half done : Client objects and the interfaces related to them do manage the username, so I added a feature to keep the password, which I name `Givenpassword` inside the code. I was surprised, because I had to make changes in three different places (three different files) of the upstream code to achieve it, and at least one function `Givenpassword()` is quite weird since it cannot actually access the given password.
2. I believe that the usage of regexps which I propose is rather harmless: they are only used to filter relevant parts in a user's LDAP record; can one forge a regexp which would trigger too much computing in the server? This one must have enough permission as to modify groups JSON files, and create for example a world-open group which would be more cumbersome. However, if you prefer, regular expressions can be replaced by plain strings, at the expense of a lesser expressive feature.

**Comment by jech** [comment]
Moved discussion to #84.

**Comment by jech** [comment]
Galene now support third-party authorisation, as desribed in https://lists.galene.org/galene/87ley8e245.wl-jch@irif.fr/  It is now possible to integrate Galene with other authorisation systems, with no changes to the server.

A sample authorisation server is available here: https://github.com/jech/galene-sample-auth-server  All that's needed is to write a commplete authorisation server that speaks LDAP.

For simplicity, I'm planning to keep the native authorisation system, but I won't be expanding it any further — anyone who has more complex requirements should be using their own authorisation server.
