### ISSUE TITLE
Group Password mechanism appears broken: allows any user with any password to login

### ISSUE THREAD

**Issue by cvmiller** [jech/galene#123]
Running version  0.4.2 (from the Changes Doc)

I have followed the example of the most basic group:

```
$ cat name.json 
{
    "op": [{"username": "fred", "password": "mypass"}],
    "presenter": [{}]
}

```
Yet any user with any password can log into this group. Perhaps I don't understand the authentication mechanism, but I expected that only "fred" would be allowed to login

**Comment by jech** [comment]
This is the expected behaviour: `[{}]` means any user with any password, which is useful for lectures.  If you want only `fred` to be able to login, say just
```
{
    "op": [{"username": "fred", "password": "mypass"}]
}
```

**Comment by cvmiller** [comment]
Thank you for the clarification. I have it working now.
