### ISSUE TITLE
Share audio from browser tab

### ISSUE THREAD

**Issue by aksdb** [jech/galene#124]
When sharing a browser tab with a video playing, it would be nice if the audio is also transmitted. That would simplify showing videos from YouTube or other embedded video sources.

(Sharing sound of the whole desktop when sharing the desktop would also be cool, but from what I can tell this is a lot harder depending on the operating system and/or browser.)

**Comment by jech** [comment]
How do you envision the user interface?  Should we share audio by default, or should there be a toggle?  Where should the toggle be located?

**Comment by aksdb** [comment]
Hmm, good question. Intuitively I would say that when sharing a tab, audio from that tab should just automatically be shared as well. Similarly could be argued for sharing a window - maybe someone wants to share a multimedia application?

For sharing the desktop I think a good spot might be the "media options". Another checkbox named "share desktop audio".

**Comment by jech** [comment]
Unfortunately, that cannot be done: we need to decide whether we wish to share audio or not *before* showing the dialog box that allows the user to pick the screen, window or tab to share.

**Comment by aksdb** [comment]
Then a setting named "screen share includes audio" (media options, I think).

Generally I could also imagine a drop down when clicking on "share screen", but then it would always be an additional click, even when the feature is not wanted/needed. So unless it turns out that it's used very often, a more passive option is likely better, even if that means that in the case where you need audio, you need to think about this additional option in advance.  An upside however would be, that you don't accidentally forget that you had it enabled when you want to share something ... :thinking:

**Comment by jech** [comment]
Done in 296fe622dfebd8f3cc90491c82ef7ef9888b0bd6.

**Comment by aksdb** [comment]
@jech Very cool! Thank you so much! I'll test-drive this soon :-)

**Comment by jech** [comment]
You may test it straight away at <https://galene.org:8443/group/public/>.
