### ISSUE TITLE
documentation typo ?

### ISSUE THREAD

**Issue by Miroslav36** [jech/galene#133]
Hello,

First of all thank you for creating this software. I've installed it using Yunohost.

I would like to suggest two little changes to the galene documentation that could be helpful for "basic" level users like me :
I share these two points because when I've created the new json file, a "server internal error" message appeared.

1- in https://galene.org/README.html I think that a coma is missing at the end of the "presenter" line
the A typical group definition file looks like this:
{
    "op":[{"username":"jch","password":"1234"}],
    "presenter":[{}]    --> should this be "presenter":[{}], (with a coma) ?
    "allow-recording": true,
    "allow-subgroups": true
}

2- When creating a new group, the owner of the file should be galene:galene (at least for yunohost install). At first I've created my json file with root and the owner was root:root. Maybe the ownership information could be added ?

Thank you.

**Comment by jech** [comment]
Fixed 1.  As to 2, it's specific to Yunohost, the file must be readable by whatever user Galene is being run as.
