### ISSUE TITLE
issue with recording

### ISSUE THREAD

**Issue by Miroslav36** [jech/galene#134]
Hello,

I am currently running Galène 0.5 on my yunohost instance (latest version 4.3.6.2 (stable), Galene package 0.5~ynh1) .
It runs on a VPS 1 Vcore 4 Go Memory and 40Go disk space left.

I am confused with recordings and will try to explain it : 

When recording without sharing a screen, the recorded webm video usually* works fine (video and audio OK) but when I record a other conference with a shared screen then both webm videos (speaker's and the shared screen) are not working well (sound track has only a few seconds left as if the beginning of the audio recording has been erased and it started almost at the end + video starts normally but stops/freezes when screen is shared)

* "usually" because it happens that the recorded videos of the speaker has no sound and picture freezes, sometimes I  just get an empty video (just a black image) and no sound. I think that it happens when I use the /record /unrecord twice during the same conference (maybe I am not supposed to do that ?) 

With the previous version of Galene (0.4.4) I've also had issues with sound not recorded at all.

I wonder if this is a server issue (I've watched CPU during a meeting and it is mostly around 2 / 3 %, never went over 35% during a few seconds), what should I check ?
Could this be an issue with the Yunohost's Galene install ?

I hope my explanations are understandable. 
Thank you for your help and advice for troubleshooting this issue.

**Comment by jech** [comment]
Yes, we're having issues with recording.  It's improved since 0.4.4, but it's still not correct.

**Comment by jech** [comment]
More improvements in db21575df31662426a2de44192198d9db47d5320.
