### ISSUE TITLE
Not being able to see others video/audio, revival

### ISSUE THREAD

**Issue by pjmkrpg** [jech/galene#137]
Galène used to work perfectly on my debian 11.2 server but now by reusing it after several months of inactivity (no clue about what could have happened in the meantime), I obtain the same problem as #86 : each user can only see his own video/screen/audio, the others appear in black. Test was between firefox for linux and firefox for android.
I launch the server with
 `./galene -turn my.public.ip:1194 -udp-range 8000-8020`
and it says
```
2022/03/17 19:16:23 Starting built-in TURN server on my.public.ip:1194
2022/03/17 19:16:24 Relay test successful in 32.820282ms, RTT = 356.298µs
```
Netcat gives the following output
```
$ nc -v  my.domain.name 1194
Connection to my.domain.name (my.public.ip) 1194 port [tcp/openvpn] succeeded!
```
Typing  `/relay-test` in the chat answers `Relay test failed: Error: timeout`.
In my freebox parameters the following redirections are active
```
8443(tcp,udp) -> server
1194(tcp,udp) -> server
8000:8020 (udp) -> server
```
The corresponding ports are of course allowed by ufw on the server.
Could you help me?

**Comment by jech** [comment]
```
$ nc -v  my.domain.name 1194
Connection to my.domain.name (my.public.ip) 1194 port [tcp/openvpn] succeeded!
```
From inside or outside the network?

**Comment by pjmkrpg** [comment]
From outside. Inside I obtain 
```
$ nc -v my.domain.name 1194
DNS fwd/rev mismatch: my.domain.name != ph489-1-my.public.ip.fbx.proxad.net
my.domain.name [my.public.ip] 1194 (openvpn) open
```

**Comment by jech** [comment]
That's very weird.

Please confirm that you can connect to port 1194.  Stop Galene, then on the server that usually runs Galene do:
```
nc -l -p 1194
```
From outside the network, do `echo 1234 | nc ...`, and type a few lines; you should see the instance of `nc` running inside the network display the string.

**Comment by pjmkrpg** [comment]
I confirm that strings sent with nc from outside the network are perfectly echoed by nc listening on port 1194.

**Comment by jech** [comment]
I'm at a loss here.  The failure in `/relay-test` indicates that the TURN server could not be reached, or that it doesn't work.  Yet, your test indicates that the TURN port is open from the outside.

**Comment by jech** [comment]
Seems like a local configuration issue, the mailing list is a better place to discuss such problems.  Please reopen if you feel this is a bug in Galene.

**Comment by pjmkrpg** [comment]
Hi, I still have the exact same issue while trying to run Galene with a different Internet box (SFR, IPv6 + IPv4/NAT configured). However it seems to be now browser-dependent as everything works well as soon as one client uses chromium instead of firefox. The /relay-test still fails though, but with no apparent  consequences.
So I conclude that this issue is the same as [that one](https://github.com/jech/galene/issues/49).

**Comment by jech** [comment]
@pjmkrpg this looks like [Firefox bug 2033783](https://bugzilla.mozilla.org/show_bug.cgi?id=2033783).  Please upgrade to Firefox 151 or later.
