### ISSUE TITLE
Menu disappears behind broadcasted files

### ISSUE THREAD

**Issue by ericgaspar** [jech/galene#139]
Depending on where you click, the contextual menu appears in different places and behind the show chat icon and the broadcasted file.

![Capture d’écran 2022-03-26 à 14 08 06](https://user-images.githubusercontent.com/46165813/160240882-fc384a1a-dc70-4285-8f73-fd18c3f21630.png)

![Capture d’écran 2022-03-26 à 14 07 08](https://user-images.githubusercontent.com/46165813/160240889-93fd0402-2b86-4164-aaff-81f79cdbe1e3.png)

**Comment by jech** [comment]
Yep.  Unfortunately, the `galene.css` file is a mess — it's abusing both `z-index` and `!important` to do all sorts of weird things, which means that any addition requires changes all over the place.

**Comment by ericgaspar** [comment]
`z-index: 1010;` is missing in `static/external/contextual/contextual.css` for `.contextualMenu` 

(chat button being `z-index: 1002;`)

Why 1010? ¯\\\_(ツ)_/¯ (I am not up-to-date in css...)

**Comment by jech** [comment]
I don't want to be modifying the files in `external`, it will make upgrading a pain.  We must fig Galene's CSS so it's compatible with external libraries.

**Comment by jech** [comment]
Fixed in 96f39ca.  I'm an idiot.

(However, somebody should still go through galene.css and fix the mess.  The abuse of z-index is abhorrent.)
