### ISSUE TITLE
Get rtptime.Jiffies is zero at a while

### ISSUE THREAD

**Issue by lamhai1401** [jech/galene#140]
I'm try to debugging `func rtcpUpListener(track *UpTrack)`
Because sometime it try to call `sendSR` a lot

Here is my log file
[jiffies.log](https://github.com/jech/galene/files/9156218/jiffies.log)

 in range [04:36 -> 04:43] it always return 0.

Could you guys tell me how to fix that.

Thanks in advance!

**Comment by jech** [comment]
Thanks a lot!  I've been struggling to understand why the rate estimator was behaving strangely at times, and it turns out the bug was in rtptime!

This should be fixed by b4edb7c0c7a780d0483ea7634fa309f86aecd157.  Please reopen if you find this is not the case.
