### ISSUE TITLE
Recording issue with no usable tracks found

### ISSUE THREAD

**Issue by dwinurhadia** [jech/galene#143]
I've running galene with debian 11
When i try to `/record `its popup alert about `no usable tracks found`
is there an issue with dependency package in the installation?

**Comment by jech** [comment]
Interesting.  Could you please show your group cofiguration?

**Comment by dwinurhadia** [comment]
Hi @jech 
here is the config group name` jajal.json`

```
{
    "codecs": ["vp8", "vp9", "opus"],
    "autolock": false,
    "op": [{"username": "myname", "password": "mypassword"}],
    "presenter": [{"password": "grouppassword"}],
    "allow-recording": true,
    "allow-subgroups": true
}

```

**Comment by jech** [comment]
Does the recording work?

The message indicates that the diskwriter received a stream with no writable track.  This might happen if the client establishes a stream and is slow to actually send data on the stream.  The diskwriter should recover when the client finally starts sending data.

I don't see any good way to suppress the error message: I don't see a way to distinguish the case that the client is not sending any data (in which case you want to be informed that you're not recording anything) and the case where the client is merely slow.  I'm leaving the issue open in case I have an idea.

**Comment by dwinurhadia** [comment]
Hi @jech 
it fix by change with newer os and re-installing galene

Thank you

**Comment by jech** [comment]
Please reopen if you manage to reproduce the issue.
