### ISSUE TITLE
Selective forwarding

### ISSUE THREAD

**Issue by kiufta** [jech/galene#145]
Has galene also the _selective forwarding_ feature?

**Comment by jech** [comment]
I'm not sure what you mean.

**Comment by kiufta** [comment]
https://bloggeek.me/webrtcglossary/sfu/

**Comment by jech** [comment]
Yes, Galene is an SFU.  Please read <https://galene.org>.

Should you have any further questions, please contact us on the Galene mailing list <galene@lists.galene.org> (https://lists.galene.org/postorius/lists/galene.lists.galene.org/).
