### ISSUE TITLE
Could you provide an AppImage?

### ISSUE THREAD

**Issue by IzzySoft** [jech/galene#15]
This sounds really intriguing! But for end users, self-build is something to "scare them away" – especially with installing all the Go dependencies.

Would it be possible to provide an AppImage? That would remove those "fears" and makes it easy to try out Galene. Installation would then be pretty easy: download the AppImage, make it executable, run it.

Thanks in advance for considering!

**Comment by jech** [comment]
Please see #5.

**Comment by IzzySoft** [comment]
Well, docker is something completely different: it would require a docker daemon plus all its dependencies installed on the system (again nothing for a "not-so-tech-savvy user) – while an AppImage would be completely self-contained, and cover (almost?) all Linux distributions without the need of "distribution specific stuff". Maybe [deb2appimage](https://github.com/simoniz0r/deb2appimage) could be used for this, should you already provide Debian packages?

**Comment by jech** [comment]
Sorry, perhaps I should have been more explicit.

I am not planning to include dockerfiles, Appimage or Debian packages, since I don't have the manpower to maintain them.  On the other hand, I'll be glad to link to packaging that other people maintain from the galene.org web page.

**Comment by IzzySoft** [comment]
Thanks for the explanation, @jech – that's of course totally understandable (though not what I hoped for). Being a maintainer for some larger projects, I fully understand (we're also permanently understaffed – which is why I hoped I could use Galene for some "teaching sessions" to get possible new contributors started).

As demand seems to be there, hopefully someone jumps in. Suggestion: Why not have one issue open for these things (like, "packaging for distribution" as title, and a list of "wanted formats" in the initial comment) and add a "help wanted" label? Would avoid the very same question permanently being re-asked by users – and explained by you, while hopefully getting some packagers on-board. You could even "pin" that issue so it stands always-on-top and noone can miss it.
