### ISSUE TITLE
Allow to prefill username/password through URL param

### ISSUE THREAD

**Issue by spaetz** [jech/galene#158]
If I want to invite specific people into a group, it would be great to be able to send them a single link which has a username/password prefilled, so that all they need to do is hit "connect". This is similar to an invitation with an infinitely valid token, which would prefill the username field to something (like "Student" :-)) that could still be modified by a person before joining.

So, effectively something like the following should work:

https://galene/group/roomA/?token=XXX&username=Student_A or even
https://galene/group/roomA/?password=XXX&username=Student_A (in case I don't want to use the token mechanism)

**Comment by jech** [comment]
This is already implemented, albeit in a slightly different manner: the token may contain a username.  Please join a group as an administrator, then click on your own name in the users list, and choose « invite ».  The dialog box contains a field for the username; if you enter a non-empty username, the token will cause immediate login and use the username contained in the token.

Of course, this means that you need to generate a separate token for each user.  If you want to do that for many users, we'll need to think together how to automate the process.  (I'm thinking of either a functionality where you import a list of users in a text file and Galene generates one token per user, or an easily scriptable REST-like interface.)
