### ISSUE TITLE
WHIP: panic on /whip

### ISSUE THREAD

**Issue by erdnaxe** [jech/galene#159]
While testing `whip` branch, I got a panic at https://github.com/jech/galene/commit/7c2bc04359466ed81098ce77477fb47d4b426557#diff-b816908f2b221093098f09c7d651135fb78dec9ceacff38d82dccc922e528005R275.

I believe this happens when a POST request is sent to `/whip` without a trailing `/`.
Maybe this condition should check `p` length before `p[:6] != "/whip/"` ?

**Comment by jech** [comment]
Right, thanks.  I'll keep that in mind when I update the whip branch.

**Comment by jech** [comment]
The whip branch is obsolete, please use the branch whip2 instead.
