### ISSUE TITLE
Browser refuse to connect to WebSocket when using insecure Galene behind a reverse proxy

### ISSUE THREAD

**Issue by erdnaxe** [jech/galene#160]
When running Galène in `-insecure` mode, `groupStatus.endpoint` will start with `ws://`.

This is problematic when using a HTTPS reverse proxy pointing to a insecure (HTTP) Galene as the browser will refuse to connect to `ws://` from a `https://` website.

A dirty fix could be:

```diff
--- a/static/galene.js
+++ b/static/galene.js
@@ -3492,7 +3492,10 @@ async function serverConnect() {
     let url = groupStatus.endpoint;
     if(!url) {
         console.warn("no endpoint in status");
-        url = `ws${location.protocol === 'https:' ? 's' : ''}://${location.host}/ws`;
+        url = `ws://${location.host}/ws`;
+    }
+    if (location.protocol === 'https:') {
+        url = url.replace("ws://", "wss://");
     }
 
     try {
```

**Comment by jech** [comment]
This should be handled automatically if you set `proxyURL` in the config file.  Can you confirm that `proxyURL` is set to an HTTPS address?  Please see the code at https://github.com/jech/galene/blob/master/group/group.go#L1256

**Comment by jech** [comment]
Please reopen if setting `proxyURL` doesn't fix the issue.
