### ISSUE TITLE
No entry in the Free Software Directory yet

### ISSUE THREAD

**Issue by bhaible** [jech/galene#161]
The [Free Software Directory](https://directory.fsf.org/wiki/Main_Page) does not list Galène so far.

To have it listed, someone should fill out [this form](https://directory.fsf.org/wiki/Form:Entry).
For reference, here is the one for Jitsi Meet: https://directory.fsf.org/wiki/Jitsi-Meet

**Comment by jech** [comment]
Hi Bruno, it's been a long time!

Done: https://directory.fsf.org/wiki?title=Galene
