### ISSUE TITLE
When using any filter and trying to logout we get an error "Uncaught TypeError: c.sc is null"

### ISSUE THREAD

**Issue by zerolabnet** [jech/galene#167]
When using any filter (mirror-h, mirror-v) and trying to logout of the group (button Logout), we get an error in the browser console:
```
Uncaught TypeError: c.sc is null
    setStream https://galene.org:8443/protocol.js:1161
    removeFilter https://galene.org:8443/galene.js:1107
    onclose https://galene.org:8443/galene.js:1224
    close https://galene.org:8443/protocol.js:1221
    onclose https://galene.org:8443/protocol.js:312
```
The error occurs here in the removeFilter function: _c.setStream(old.inputStream);_

**Comment by jech** [comment]
Thanks, fixed in cc2ed144843ef5ebc4353b7096708355cab3b992.
