### ISSUE TITLE
some awkward behavior in the `op` field in the group json config

### ISSUE THREAD

**Issue by Krastanov** [jech/galene#17]
First of all, this is an amazing tool! Thank you!

I set up a public room on my server and the following two configs work fine:

```
{
  "public": true,
  "op": [{}],
  "presenter": [{}],
  "max-users": 100
}
```

```
{
  "public": true,
  "op": [{}],
  "presenter": [],
  "max-users": 100
}
```

But this last one does not work:
```
{
  "public": true,
  "op": [],
  "presenter": [],
  "max-users": 100
}
```

It reports the following when I try to log in with arbitrary user name and empty password:
![image](https://user-images.githubusercontent.com/705248/103142294-cd822d80-46ce-11eb-950b-5d2a65c3b9d8.png)

The change was turning `"op": [{}]` (working) into `"op": []`. It is subtle and minor thing, and not really a problem, but I was surprised it is not working, especially given that an empty list seems like the semantically correct line. Given that it is a minor two-character change, I imagine I was not the only one who had a non-working public room on their first attempt.

**Comment by jech** [comment]
Fixed in 2ec0c0145812c943fefcebe6906b2607a64ddd23.
