### ISSUE TITLE
Ldap integration 

### ISSUE THREAD

**Issue by gedw99** [jech/galene#172]
https://gitbub.com/jech/galene-ldap No longer exists ?

I would like to hook up galene to glauth.

https://github.com/glauth/glauth

**Comment by jech** [comment]
There's a typo in your URL.  The proper URL is https://github.com/jech/galene-ldap, which is still active.

> I would like to hook up galene to glauth.

Fell free to contact the list at <galene@lists.galene.org> if you need help, or just to tell us how it goes.
