### ISSUE TITLE
TypeError: navigator.mediaDevices is undefined

### ISSUE THREAD

**Issue by kovmir** [jech/galene#174]
Using [d16c680](https://github.com/jech/galene/commit/d16c680f998af75dfea23fca460055d33501a775). I have set up galene according to [the guide](https://galene.org/INSTALL.html), but I launch it like that `./galene -http :8444 -insecure`.

I can reach web UI and enter a room, but if I click `Enable` to show my camera, I get a red pop up saying `TypeError: navigator.mediaDevices is undefined`. In the mean time everything works on the official demo instance.

**Comment by kovmir** [comment]
The browser does not expose my camera over HTTP, only HTTPS.

**Comment by jech** [comment]
Right, that's a documented limitation.  I'm reopening this issue, since we should check for this case and disable the *Present* button.

**Comment by jech** [comment]
Fixed in 96e2db0.
