### ISSUE TITLE
Websocket upgrade: websocket: request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by kovmir** [jech/galene#175]
I want to run `galene` behing `nginx` proxy pass, this is my proxy config:
```nginx
location / {
        proxy_pass http://localhost:8444/;
}

location /ws {
        proxy_pass http://localhost:8444$request_uri;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
}
```
My `data/config.json`:
```json
{
        "proxyURL": "https://mydomain.example/"
}
```
`galene` server logs (errors) as I press `Connect` on web UI:
```
Websocket upgrade: websocket: request origin not allowed by Upgrader.CheckOrigin
```
This is a VPS with a public IPv4 address.

**Comment by kovmir** [comment]
Thank you! It works. By the way what do you have in `conf.d/proxy_params`?

**Comment by jech** [comment]
Glad the issue is solved.

Another solution would be to add the `publicServer` option in `config.json`, which disables origin checks.

**Comment by kovmir** [comment]
@jech, should it not be mentioned in [Running behind a reverse proxy](https://galene.org/INSTALL.html#running-behind-a-reverse-proxy)?
