### ISSUE TITLE
Error establishing WebSocket connection using iOS Safari

### ISSUE THREAD

**Issue by apankrat** [jech/galene#18]
Hi Juliusz,

Thanks for the project. Picked it up from a mention on HN the other day. I absolutely love how uncomplicated the setup is.

I did run into an issue when trying to log into Galene using Mobile Safari (iPad).

More specifically, using a Debian 10 VM with Go 1.15.2, cloned galene repo, built it, created a cert, started with ./galene.

In Firefox on Windows - can connect to https://$ip:8443 and log in. That is, works as expected.

In Safari on iPad - can connect to https://$ip:8443, but a log attempt fails with `Couldn't connect to wss://$ip:8443/ws`.

I can however connect and log into your demo server at https://galene.org:8443.

Dug around a bit and found a [comment](https://stackoverflow.com/q/57723263/1877011) saying that the iOS doesn't allow WSS with self-signed certs. Seemed like a long shot, but still symlinked ./data/cert.pem from ./static and added it to the iOS trust store (by visiting https://$ip:8443/cert.pem and following the prompts). This eliminated the "unknown cert" warning when opening the page, but the log in error remains.

This has gotta be some well-known caveat... Do you happen to know what the heck is going on here?

Regards,
Alex

**Comment by apankrat** [comment]
In addition to installing the cert on iOS, I also tried setting the certificate subject (CN) to the IP address of the machine (`$ip`). This also made no difference.

**Comment by jech** [comment]
I believe you'll have more success contacting an Apple software forum, or perhaps Apple's technical support.  I'm leaving this issue open a few more days in case somebody can help.

**Comment by apankrat** [comment]
When there's an undocumented obscure problem with a platform, suggesting to contact its vendor tech support is a dry joke that I too like to make. In my case it's usually involves Microsoft, though I have to admit it works even better with Apple :)

Please keep this open. I'll run more experiments in the next few days. I want to try using a CA-signed cert vs a self-signed one, see if it makes a difference. I will also get a proper cert from a trusted CA too, confirm that this works.

I think it won't hurt to update the summary blurb as per findings, because it currently says "The client [snip] works on recent versions of all major web browsers, both on desktop and mobile", while clearly there are some low-hanging caveats.

**Comment by jech** [comment]
> suggesting to contact its vendor tech support is a dry joke

I'm sorry for the cheap shot.  I just couldn't resist.

**Comment by apankrat** [comment]
I managed to get it working with self-issued certs. This requires first creating a self-signed \_CA\_ cert, installing it on the iOS device, enabling "full trust" for it and then using it to sign a cert for Galene to use. Not terribly hard to do, but annoying nonetheless (which I guess _is_ the goal).

I will write it up tomorrow and post the details.

**Comment by jech** [comment]
Not an issue with Galène.

**Comment by apankrat** [comment]
In case if anyone runs into this issue, here are the instructions on a self-signed certificate setup for wss:// that works with Mobile Safari (iOS) - https://gist.github.com/apankrat/612dde3d7f01c4713c9579b0a94d9547
