### ISSUE TITLE
browser to remember username and password

### ISSUE THREAD

**Issue by aguaviva** [jech/galene#180]
It could be done by:

- having the browser remember the credentials (via a cookie?)
- have the url include the group, username and passwd

Hopefully this is an easy one and with just one click we can join a group

Cheers.

**Comment by jech** [comment]
This is already implemented except that we store an opaque token in the URL, which avoids leaking passwords.

Log in to your favourite group as op, then click on yourself in the menu, and choose *Invite user*.  Fill in the fields, and the server will generate a URL that allows you to join with just a single click.
