### ISSUE TITLE
installing instructions not clear at all

### ISSUE THREAD

**Issue by nikto1** [jech/galene#183]
Hi there,

maybe for you guys that are working on the project the installation process is crystal clear but for me - and i think for other people too - not at all.
I have enough resourses to run also other stuff there, not just galene. Based on this so is it possible to run galene with other stuff installed. From what i've understand not at all.

1)  `Then connect to https://localhost:8443 and choose “test”.` --> you're supposing galene is installed locally and there is already an SSL certificate installed? E.g. in my case i've installed galene for a user on an online server in a subdomain and when i try to access https://subdomain.example.com:8443 it gives me a connection reset error although i have a ssl certificate for the domain + subdomain. Port 8443 is obviously open.
2) `mkdir groups vi groups/name.json` --> where should the folder "groups" be made? Inside the root directory or in the folder where galene is installed? If so, wouldn't it be better to make an empty folder/ file named "groups/name.json" by default? Otherwise you're supposing everyone has access to the whole server?
Note: if i start galene from e.g. _"home/users/server_user/www/galene"_ i got a _"Group file ./groups/: lstat ./groups/: no such file or directory"_ error but if i start galene from within the installation (_./galene_) the folder "_groups_" is found.
3) `./galene &` --> please clarify, what does this do, what happens and which user/ where should it be executed? Should it be executed as "root"? If so, i suppose the whole installation goes inside the "/" folder. If the answer is positive, how to deploy the server for a specific user on a specific domain?
4) `Deploy to your server` --> Not clear at all. E.g. where's the "data/ice-servers.json" folder/ file, how to stop galene/ build in turn server, what are the possible configuration options, ecc.? Maybe put a default configuration somewhere with some comments so people know how to configure it.
It would also be good to give some advices, e.g. if you have HSTS enabled, a self-signed SSL will interrupt the connection so a valid certificate is required. As letsencrypt renews certifcates each 3 months the whole copy/paste process of the *.pem files should be executed with a cron job or stuff like that.
5) `Connectivity issues and ICE Servers` --> same as 4

Would be great to make a more comprehensive guide so i could try it out.

Thanks a lot in advance

**Comment by jech** [comment]
> maybe for you guys that are working on the project the installation process is crystal clear but for me - and i think for other people too - not at all.

Thank you for your feedback.  Installing from source is always more involved than installing from a distribution.  Please consider using [Yunohost](https://yunohost.org/), which provides an automated installation procedure for Galene.

Should you insist on installing from source, please consider subscribing to the [galene@lists.galene.org](https://lists.galene.org/) mailing list, which is more suitable for support requests than this issue tracker.

**Comment by dashohoxha** [comment]
@nikto1
These scripts try to automate the installation of Galene:
https://gitlab.com/docker-scripts/galene
I use them for myself. Can you have a look and see if they help you somehow?
