### ISSUE TITLE
Would it be possible to use the github "releases" feature

### ISSUE THREAD

**Issue by kyzh** [jech/galene#187]
First, thank you for this great piece of software.

Now, there is a RSS feed available on the releases URL https://github.com/jech/galene/releases 
This is not the case for tags URL https://github.com/jech/galene/tags which is currently used to track releases.

I use the RSS feature to alert me when a new version drop, hence why I am asking.
If you rather not use the "releases" feature, would you mind having a release or a security mailing list with a separate atom feed than the existing mailing list.

Thank you again

**Comment by jech** [comment]
> This is not the case for tags

This works for me: https://github.com/jech/galene/tags.atom

**Comment by kyzh** [comment]
I was pretty sure I tried before opening the issue and there was no feed.
But works now indeed, Thanks!

**Comment by jech** [comment]
Glad it works for you.
