### ISSUE TITLE
Same user can login twice/ thrice/ ecc..

### ISSUE THREAD

**Issue by nikto1** [jech/galene#189]
As per title, a user can login as many times as he wants on multiple windows, multiple browsers, from multiple locations, ecc.
Shouldn't there be a check if a user is already logged in?

**Comment by jech** [comment]
> a user can login as many times as he wants

It's a useful feature, we often simultaneously use a smartphone for video and audio and a laptop for the slidees.

> Shouldn't there be a check if a user is already logged in?

No, why?

**Comment by jech** [comment]
> Other people can impersonate you.

Only if they have your password.

> IMO at least there should be a message that you're already logged in from another device/ip/ browser.

Sure, I'd be willing to accept a patch for that.  You'll want to check in `onJoined`, and call `displayWarning` if the username is a duplicate.

**Comment by jech** [comment]
There is no notion of user identity in Galene.  "Two distinct users" is not a notion that is well defined in Galene: if two clients use the same username, Galene does not know whether it's two distinct users or the same user that connected twice.

On the other hand, the notion of "the same username" is well defined.  Be aware, however, that the username that a client uses is not necessarily identical to the username that it used to login (a token can change the username).

**Comment by jech** [comment]
I'll be glad to have a look at your patch.  I don't know if I'll merge it, since we usually use a single token for all the students at a given lecture.
