### ISSUE TITLE
Feature request: log ip + username when they join a room

### ISSUE THREAD

**Issue by ian-kelling** [jech/galene#191]
I'd like to be able to block a user on the firewall level if needed.

**Comment by ian-kelling** [comment]
Additional note: in other applications ip logs, user agent strings are often logged and that would be nice to see too.

**Comment by ian-kelling** [comment]
I think you are misunderstanding the issue completely.

You install Galene, post it to the internet, no passwords, anyone can join. Someone shows up anonymously, and ruins it with spam or whatever else. What do you do using free software? There are 2 options: #1 generally abandon anonymous chat entirely by asking everyone to identify themselves in some way, and then hand out user names and passwords. #2 ban the offender using the information they gave you: their ip address and user agent. Every web server logs ip addresses and user agents, trying to keep this out is misguided.

**Comment by jech** [comment]
Here's a prototype:  https://github.com/jech/galene/tree/spy-on-users

It adds a command `/identify` and an entry to the context menu of a user.  The command is limited to the group op, and it sends a warning to the user being spied upon.

I've based it on Galene 0.8.2 for your convenience, but it's not going into 0.8, if it goes in it will be in 0.9.

**Comment by TechnologyClassroom** [comment]
I tested this branch with identify and it works as expected. Thank you!

**Comment by jech** [comment]
Merged in a76f225.
