### ISSUE TITLE
/kick (anon) results in "Error: Unknown user (anon)"

### ISSUE THREAD

**Issue by ian-kelling** [jech/galene#192]
If a user joins without a username, they become (anon). Multiple (anon)
users are allowed. Moderation actions cannot be run against (anon) users
in the traditional way.

/kick (anon) results in "Error: Unknown user (anon)"

Using inspect element on the user, we can see unique names like
user-1bb1b976001905674edf7386e26a8ec6. If you take the string
1bb1b976001905674edf7386e26a8ec6, you can take moderation action with
that.

/kick 1bb1b976001905674edf7386e26a8ec6

It would be nice to not need to inspect element.

To solve this, anon users could have a number automatically appended to their username, or there could be an option to require users to input a username.

**Comment by jech** [comment]
What about clicking on the username in the list on the left and choosing "kick"?  Does that not work?

**Comment by ian-kelling** [comment]
Oh, it does. Thanks! Sorry I missed that.

**Comment by TechnologyClassroom** [comment]
If two users have the same username, the chat username does not distinguish a difference between them. Not sure how we could tell which one to kick.

**Comment by jech** [comment]
You currently cannot.  Suggestions for improving the situation are welcome.

However, please be aware that the ability to log in multiple times with the same credentials is a feature: for example, when a user doesn't have a webcam, they can use both their smartphone (for audio and video) and their computer (for screen sharing and chat).

**Comment by TechnologyClassroom** [comment]
I can see that use case. I suppose what I mentioned should be a separate issue.
