### ISSUE TITLE
best way to send the URL to another user for impromptu video conferences.

### ISSUE THREAD

**Issue by gedw99** [jech/galene#195]
I am using galena in a non profit org. its really great in its simple approach and no dependencies

I was wondering about how people message others to get them into a room for a web conference ? I know it can be a Cal event, but what if it's more impromptu ? I prefer to NOT have to send out the URLS over another medium like email or SMS..

**Comment by gedw99** [comment]
I was thinking about this and way realising that maybe if I wrapped this in a Webview, then users can install galene.  This would allow notifications to be sent over the Apple and Google system to the App.    

there is also https://github.com/binwiederhier/ntfy, which is a notification system that is installable as a Web App on Desktop and Mobile. 

Some users won't have the App installed, and so there is I guess always the need to sometimes send a SMS message to a user with a URL to the Web App Url.

**Comment by jech** [comment]
If you click on your own username in the left panel, and pick « invite user », Galene will generate a URL that allows password-less login.  If you're on mobile, it will open the native « share » dialog, so you can easily send the invite over SMS or whatever.

The UI needs improvement, granted.  I'm horrible at HTML and CSS, so contributions in this area are very much welcome.

**Comment by jech** [comment]
Closing this issue since there are no actionable issues.  Please consider using the mailing list for discussions.
