### ISSUE TITLE
 Feature request: Add UUID to username metadata of chat

### ISSUE THREAD

**Issue by TechnologyClassroom** [jech/galene#196]
If two people login with the same username such as two people with the same chosen name or no username (anon) and then one of them says something inappropriate in the chat, there is no way for the operator to tell which user should be kicked.

As a technical measure, adding a UUID such as the string that looks like user-1bb1b976001905674edf7386e26a8ec6 when you look at the user list could maybe be added to the message-user class of each user entry in the chat.

Edit: Alternatively, the chat log including IP addresses could be logged in the server-side.

**Comment by jech** [comment]
What about having a context menu on chat entries that allows:
  - identifying the user who sent the chat message (see #191);
  - removing the message from the chat for all users (see #194);
  - kicking out the user who sent the chat.

**Comment by jech** [comment]
Done in e68ff86.  The menu is bound to double-click, since otherwise it would interfere with copy-paste.

**Comment by TechnologyClassroom** [comment]
I tested this and this works as long as the account is still logged in. Thank you!
