### ISSUE TITLE
example config and groups

### ISSUE THREAD

**Issue by gedw99** [jech/galene#198]
could an example folder be added that has working config.json and 1 or 2 groups json files ?

it will make it easy to learn how the system works and also to debug and do PR's

**Comment by gedw99** [comment]
If these config files can be released with tags then the code and config will stay in sync, allowing easier regression testing and setup too.

https://github.com/jech/galene/releases/tag/galene-0.8.2 for instance cold have the config.json and group-x.json files with it.

**Comment by jech** [comment]
> could an example folder be added that has working config.json and 1 or 2 groups json files ?

There's an example configuration file in the documentation: https://galene.org/README.html#the-global-configuration-file

There are three example group files in the documentation: https://galene.org/README.html#examples

> allowing easier regression testing

We already test the parser: https://github.com/jech/galene/blob/master/group/description_test.go

**Comment by gedw99** [comment]
seems docs and code are maybe out of sync or I am not configuring correctly. 
Hence why sample json files would be good.

```sh
       mkdir -p $(DATA_ROOT)
       cp config.json $(DATA_ROOT)/

	mkdir -p $(DATA_ROOT)/groups
	cp group-x.json $(DATA_ROOT)/groups/

	mkdir -p $(DATA_ROOT)/recordings

	galena -data $(DATA_ROOT) -insecure -static $(MAIN_NAME)/static -groups $(DATA_ROOT)/groups -recordings $(DATA_ROOT)/recordings

```

config.json
```json
{
    "admin":{"root": {"password":"secret", "permissions": "admin"}},
    "writableGroups": true,
    "publicServer": true
}
```

group-x.json
```json
{
    "displayName": "main group",
    "description": "main group for testing",
    "contact": "gedw99@gmail.com",
    "comment": "comment test",
    "users":{
        "jch":  {"password":"1234", "permissions": "op"},
        "john": {"password": "secret", "permissions": "present"}
    },
    "fallback-users": [
        {"password": {"type": "wildcard"}, "permissions": "present"}
    ],
    "allow-recording": true,
    "auto-subgroups": true,
    "public": true
}
``

**Comment by gedw99** [comment]
here is the prob

wiki and readme are def out of sync for examples of config 

anyways...

**Comment by jech** [comment]
The online docs are for the master branch, while you're running the 0.8 branch.  Please use the docs that came with your version of Galene.
