### ISSUE TITLE
Trying to instal...

### ISSUE THREAD

**Issue by Attil69** [jech/galene#20]
Hi I discovered galene yesterday and just love it. it's simple and very sober on ressources. I tried to install it on my litlle raspberry pi4, and succeed a simple install without turn server. But I use nginx and forced https. and when I go to my galene instance, it says : "Client sent an HTTP request to an HTTPS server."

What should I do to use it behind a nginx reverse proxy ?

Tx for this great software.

**Comment by jech** [comment]
You need to use an `https` URL in your `proxy_pass` statement, not `http`.  This will be avoidable once I apply https://github.com/jech/galene/pull/16.

P.S. Please note that this is an issue tracker; for help requests and general discussion, please use the mailing list.
