### ISSUE TITLE
Absolute→Relative paths in static files

### ISSUE THREAD

**Issue by vanrein** [jech/galene#209]
I was happy to find the resolution in https://github.com/jech/galene/issues/178 because I would like to run Galene as part of a larger webserver, were it runs under a non-empty path.

The static files are full of absolute references, starting with `/` and that means they don't work out of the box.  I could edit manually, but that discourages from updates and won't build into a general configuration flow I'm making (and [sharing](https://gitlab.com/arpa2/mkroot/)) for construction of a set of interconnected service containers.

Is there a way to make the static files less set on their absolute positions?  I can think of

  * Making all paths relative (that would go for `.html` and `.js` and `.css` I suppose)
  * Using a `@PREFIXWORD@` and changing it during installation or in `webserver.go`
  * Setting a `base href="/"` in `.html` and a similar form in `.js` that installer script could automatically rewrite (long patterns like `sed -i -e 's+\<base href="/"+base href="/out/of/here/"+'` should be mostly safe)

Would any of these be reasonable to you?  The work in https://github.com/jech/galene/issues/178 is incomplete without it, and automatic updates are not likely without it.

**Comment by jech** [comment]
It's a good idea, but unfortunately it's not that easy.  In Galene, the same file may be served at different URLs: the same file `galene.html` gets served whenever a user requests `/group/whatever/`, for whatever value of `whatever`.

> Making all paths relative (that would go for .html and .js and .css I suppose)

If you see a solution to the above problem, I'd be open to accepting a patch if it does not significantly increase my maintenance load.

> Using a @PREFIXWORD@ and changing it during installation or in webserver.go

Please clarify what you mean exactly.  An important feature is that it is possible to live-edit the JavaScript files of a running instance of Galene without needing to go through a compilation/installation step, are you planning to break that property?

>  installer script

There's currently no installer script in Galene, as I'm not comfortable with maintaining (and testing) a set of installer scripts that are portable between Linux, Mac OS, and Windows.  I'm not sure whether I'm willing to add one.

**Comment by vanrein** [comment]
Hello Juliusz,

> If you see a solution to the above problem, I'd be open to accepting a patch if it does not significantly increase my maintenance load.

Excellent :-) but let's discuss the approach first.  FYI, I am mostly a C/Python programmer and not yet experienced in Go, but its ideas I know well (most came from CSP/Occam and Erlang anyway).  My code would be reliable but not necessarily the Way to Go.

> It's a good idea, but unfortunately it's not that easy.

I sort-of expected that, that's why I though out aloud about options :-)

> In Galene, the same file may be served at different URLs: the same file `galene.html` gets served whenever a user requests `/group/whatever/`, for whatever value of `whatever`.

But is that a problem?  Links going to the file would be (from Go or JavaScript code).  All outgoing references to other static files would still point at a known position (under the Galene `/start/path`) and/or at a fixed position relative to those multiple positions. 

If this is indeed not a problem, then all references could be relative and one-time editing in `static/*` files would suffice.

_This reasoning goes wrong when the same file occurs at different levels, like `/start/path/galene.html` and `/start/path/group/whatever/galene.html`.  Am I correct in suspecting this does not happen?_

> > Using a @PREFIXWORD@ and changing it during installation or in webserver.go
> 
> Please clarify what you mean exactly. An important feature is that it is possible to live-edit the JavaScript files of a running instance of Galene without needing to go through a compilation/installation step, are you planning to break that property?

Breaking that property depends.  The use of  `sed -i` would break it.  The other approach, namely rewriting it in Go, would not.

Go delivers the `static/*` files with `serveFile` and `http.ServeContent` right?  The latter takes in a `ReadSeeker`, which normally reads those small files direcly; seeking allows downloads of ranges, which is barely useful for those small; the functionality must exist, but efficiency would not be important.

Then the static files could be passed through a `ReadSeeker` filter that goes through the file from the beginning and replaces a marker `@PREFIX@` (or simpler) with the `/start/path` under which Galene is run.  Seeking would be inefficiently implemented as rewinding to the start and skipping output bytes/characters.
 
> > installer script
> 
> There's currently no installer script in Galene, as I'm not comfortable with maintaining (and testing) a set of installer scripts that are portable between Linux, Mac OS, and Windows. I'm not sure whether I'm willing to add one.

This makes sense, because you are dealing with Go.  I deliberately want to insert it into a target structure and would be willing to do such things as part of that, but it would have to be reliable across versions.  Also for maintenance reasons :-)

Thanks for discussing!
 -Rick

**Comment by jech** [comment]
> All outgoing references to other static files would still point at a known position

I'm not sure I follow.  The `galene.html` file contains a link to `/galene.js`.  Since the `galene.html` file can appear at various levels of the hierarchy, I don't see how this link can be made relative.

There are two solutions that I have considered:

  * have the Go code rewrite the `galene.html` file in order to contain the right relative link;
  * put the `galene.js` file at whatever URL is requested.

The former makes the code more complex and more brittle, but it's what we might end up doing unless a better solution is found.  As to the latter, it is completely unacceptable to me, since it would break caching.

It looks from the rest of your mail that the former is what you envision, but I still hope we can find a less brittle solution.  Please note that I won't accept any PR that breaks HTTP caching and conditional requests.

> I deliberately want to insert it into a target structure and would be willing to do such things as part of that, but it would have to be reliable across versions.

I'll let you on a secret: I actually install the instance at https://galene.org:8443 using a script, and the script does some patching of the HTML/CSS/JS.  Please don't tell anyone.

**Comment by vanrein** [comment]
If you did nothing strange, then whole filenames from `static` should popup.  So I did

```
find static/ -type f -exec sh -c 'echo "# {}" ; rgrep -n $(basename {}) $(ls | grep -v static | grep -v \.git) ; echo' \;  | less
```

In 0.9.1 this yields only a few static files mentioned non-statically,

```
# static/galene.html
webserver/webserver.go:373:     serveFile(w, r, filepath.Join(StaticRoot, "galene.html"))

# static/index.html
webserver/webserver.go:234:             index := path.Join(p, "index.html")

# static/common.css
webserver/webserver.go:738:     fmt.Fprintf(w, "<link rel=\"stylesheet\" type=\"text/css\" href=\"/common.css\"/>")

# static/404.html
webserver/webserver.go:110:     f, err := os.Open(path.Join(StaticRoot, "404.html"))
```

I checked those:

  * `galene.html` occurs _only_ under `group/whatever` so it can make relative references from a `<base href="../..">`
  * `index.html` generally occurs for directories and may occur at different levels
  * `common.css` is inserted in `serveGroupRecordings` at `recordings/whatever`  and its include path can be made relative (in Go)
  * `404.html` is used from various places and can occur at various levels
 
I suppose only `index.html` and `404.html` are they only problematic files.  Two possibilities:

  1. Redirect them to the `/start/path` for Galene (easy in Go) and serve them from there
  2. Alternatively, filter them as described above

Mostly, I'd say that the relative file references are quite doable with just a bit of Go coding!

**Comment by vanrein** [comment]
Ah...

> I'm not sure I follow. The `galene.html` file contains a link to `/galene.js`. Since the `galene.html` file can appear at various levels of the hierarchy

...through subgroups, I forgot about that.  Then the precaution in italics applies.  Yes, this is a problem.  Will think it over.

BTW, I just barged in with a question, and forgot to compliment you on the lean tool that Galene is, which I love.  It also shows no signs of tracing or other impertinence, thanks :-)

**Comment by jech** [comment]
> Mostly, I'd say that the relative file references are quite doable with just a bit of Go coding!

Since I'm the one who will end up maintaining the "just a bit" of code, don't be surprised if I'm cautious.

**Comment by vanrein** [comment]
Fair and understood!

I had a go at it.  Code for `Seek()` is nasty by nature, so I commented-out that attempt and started writing to the `http.ResponseWriter` instead.  Both of this is shown in this half result:

https://github.com/arpa2/galene/commit/59fbd59587e2194b9bcd853da91d3554beea6876

Even though it is not complete, it does place a `<base href="https://example.com/x/y/z">` in the header of those files that have a `<base href="@">` and are passed through this filter.  This is working.

**Do you like this approach?**

if so, then I will complete the work:

 1. Dropping the old approach
 2. Filling the `base href` with Galène's  URL as shown in the browser
 3. Making all references in `/static` relative (to the `base href` or the fixed file location)

...and be sure to let me know if I forgot anything :-)


Cheers,
 -Rick

**Comment by jech** [comment]
I'm not sure I'm following.  It stops copying at the first occurrence of an `@` sign?

You're also going to need to handle conditional request (`If-Modified-Since` and friends).  You may use the functions in the file `precondition.go`.

Also, I wouldn't write it like this myself, I'd write a function that takes an arbitrary `io.Writer` and returns a new `io.Writer` that does the replacement.  This way, the main code can still use `io.Copy` and friends, it's only a single line that changes at the beginning of handler functions.

**Comment by jech** [comment]
I've been thinking about this some more, and I simply don't understand why this is better than doing
```
sed -i 's/href="/href="prefix/' static/*.html
```
Pros:

  1. People who want to run Galene at a non-standard location behind a reverse proxy don't need to run a trivial sed script.

However, those people who want to run Galene at a non-standard location are exactly those who should have no problem with a trivial sed script.

Cons:

  1. A bunch of additional code that I need to document, maintain and support.
  2. The data being served is no longer the data that's on disk, which makes it more difficult to e.g. run an HTML validator over the static files.
  3. Possible loss of performance as files get filtered whenever they're being served.

I'm sorry, but it looks like the cons outweigh the pros.  Please reopen if you have any further arguments.

**Comment by vanrein** [comment]
The cause of the cut-offs was sending more than announced in `Content-Length`.

I followed your idea on `io.Writer`, which worked well.  I had to make it a `http.ResponseWriter`, but the idea is the same.

**The basic idea of relative references works.**  The following patch produces a `<base href="/start/path">` in all the dynamically-placed files, which means they load their static components from a location directly under `/start/path`, like `/start/path/galene.js`.  The static files render _much more_ than they used to, but the dynamics are still all over the place.

https://github.com/arpa2/galene/commit/3a43fa6da4d5cc12080450ce3f1271248537f87b

I did not yet look into `If-Modified-Since` and `precondition.go`.  I feel shy about making a bundle of local changes without understanding the full depth of the entire process;

  - The `document.baseURI` is probably needed in JavaScript, like the comment in [`static/galene.js:4034`](https://github.com/arpa2/galene/commit/3a43fa6da4d5cc12080450ce3f1271248537f87b#diff-997f7a0d60fcf6afa0d0a255697d26340d0e70e4ebd5b342b008ab3492b66ed1)
  - The `group.Configuration` setting `ProxyURL` isn't used all over the place yet

I expect there are more tweaks that are needed, all simple, but more error-prone when i do them.  I would much prefer if you picked up these details?

**Comment by vanrein** [comment]
The `sed` approach could work for the `static/` files, although _much more reliably_ when they only occurred in `<base href="/">` form and all references would be relative to that.  This use of `sed` would overtake the `substBaseHref` wrapping would not be necessary.

> I'm sorry, but it looks like the cons outweigh the pros. Please reopen if you have any further arguments.

I appreciate the trade-off, but the Go code is _much_ more problematic to patch in this way; it has even less straightforward patterns to do this.  There are many places where it hard-codes paths under `/`, in spite of having been configured with the `ProxyURL`.  This behaviour does not seem to be consistent, so anything done with `sed -i` is likely to become a gruesome liability.

As for maintenance, I think you'd benefit form consistent handling of the prefix path in the Go and JavaScript code too, don't you?

_Please reconsider.  There are multiple ways/combinations possible but current Galène is problematic._

**Comment by jech** [comment]
Do you have an exact list of what needs to be changed in the Go code?

**Comment by vanrein** [comment]
> Do you have an exact list of what needs to be changed in the Go code?

I will need to work my way into it for that.  Effectively, that means patching the code.  That's alright I suppose.

Things I can see directly with the static-file changes are the socket (always at `/ws`) and the group status info that isn't found.  I need to patch to login and see more.  A visual detail is the entire path being shown in the top bar.

FWIW, I adapted to a 3rd form with `<base href="/">` and additional `sed -i` instructions in `INSTALL`.  Much simpler code indeed, and quite workable.

https://github.com/jech/galene/compare/galene-0.9.1...arpa2:galene:f9a457c2543b586db5059cac2a26b260e2c63890

**Comment by vanrein** [comment]
I seem to have a working setup now, with patches to the JavaScript code, all related to paths.
I will try to run a camera/speech test with friends tonight.

https://github.com/jech/galene/compare/galene-0.9.1...arpa2:galene:master

This is pulling together from a broad/searching idea into a friendly patch, IMHO.
