### ISSUE TITLE
Gracefull degradation usability

### ISSUE THREAD

**Issue by N07070** [jech/galene#21]
Hello,

I remember testing a very early version of Galène when it had no name yet, and didn't have CSS either. I also recall that it worked without needing javascript, but anyways...

I'm wondering if it would be possible to use Galène in a very basic mode when Javascript is disabled, the supported version of the browser is out of date, or the browser is not the latest Firefox, with for example only receiving the video and audio, while not being able to talk. It would make the server usable on old and less powerful hardware that some of the less fortune students use to follow there classes.

**Comment by jech** [comment]
> I also recall that it worked without needing javascript

No, it always required Javascript.

> I'm wondering if it would be possible to use Galène in a very basic mode when Javascript is disabled

The WebRTC API is only supported through Javascript — there's no way to open a WebRTC connection, there's no way to request the camera, etc. without Javascript.

I'm leaving this issue open for a few days in case somebody has an idea.
