### ISSUE TITLE
when I join the room,I don't want to auto subscribe other streams

### ISSUE THREAD

**Issue by czk630597526** [jech/galene#217]
great project ! it is lighter and readble than livekit.
will you provide golang-server-sdk in the future

**Comment by jech** [comment]
> when I join the room,I don't want to auto subscribe other streams

You can easily patch your copy of Galene, see below.  If you need it in the upstream version, we'll need to think about suitable UI.

> will you provide golang-server-sdk in the future

Yes, I will.  There is some Go client code in https://github.com/jech/galene-file-transfer, but it's incomplete, I need to move it out into a separate module and complete it.  Could you please describe your usecase?


```
diff --git a/static/galene.html b/static/galene.html
index 556eeec..6b37b8a 100644
--- a/static/galene.html
+++ b/static/galene.html
@@ -233,11 +233,11 @@
           <form id="requestform">
             <label for="requestselect" class="sidenav-label">Receive:</label>
             <select id="requestselect" class="select select-inline">
-              <option value="">nothing</option>
+              <option value="" selected>nothing</option>
               <option value="audio">audio only</option>
               <option value="screenshare">screenshare only</option>
               <option value="everything-low">low quality</option>
-              <option value="everything" selected>everything</option>
+              <option value="everything">everything</option>
             </select>
           </form>
```

**Comment by jech** [comment]
What user interface do you suggest?

**Comment by czk630597526** [comment]
What do you think of designing a conference control module that can retrieve all members and their streams in the conference, and then each member can access the streams as needed to truly achieve the selection function of SFU.
For example, in some scenarios, I don't want to see all the members, I just want to see one screen, but poll the screens of each member

**Comment by jech** [comment]
What user interface do you envision?

**Comment by jech** [comment]
I think we're not understanding each other.  Is that a feature that you want to add to the default Galene client, or is it a feature that you want to implement in your own client?  If the former, how would you imagine that it could look for the user?
