### ISSUE TITLE
Building on Debian stable (10.7) fails to find crypto/ed25519

### ISSUE THREAD

**Issue by kerneis** [jech/galene#22]
```
kerneis:/usr/local/src/galene$ cat /etc/debian_version 
10.7
kerneis:/usr/local/src/galene$ CGO_ENABLED=0 go build -ldflags='-s -w'
build github.com/jech/galene: cannot find module for path crypto/ed25519
kerneis:/usr/local/src/galene$ go version
go version go1.11.6 linux/amd64
```
It would be nice if the README specified the minimal required version of the compiler.

**Comment by MisterDA** [comment]
The file `go.mod` has a line describing the minimal version supported,
currently it is Go 1.13.
It's odd that you don't get a more explicit message, I don't know if that's
the expected behaviour or not.

-- Antonin

**Comment by jech** [comment]
Older versions of Go don't parse the `go.mod` file at all, so you don't get a useful error message.

@kerneis, you may either cross-compile from a more recent system, which is what I do, or install a more recent version of Go., https://golang.org/doc/install
