### ISSUE TITLE
iOS chrome: camera does not activate 

### ISSUE THREAD

**Issue by gedw99** [jech/galene#220]
![image](https://github.com/user-attachments/assets/718813d9-8693-488a-bde3-671d10223b02)

latest iOS , iPhone 15 max.

**Comment by jech** [comment]
Please check that camera and microphone access is allowed for the site.  (I think you need to click on the camera icon in your address bar and choose « Allow » somewhere, but I've now returned the iPad that I borrowed in order to test Galene under iOS, so I can't check.)
