### ISSUE TITLE
iOS chrome: video stream is dulled 

### ISSUE THREAD

**Issue by gedw99** [jech/galene#221]
![image](https://github.com/user-attachments/assets/167ca52e-8201-44f6-9771-14b58855f886)

**Comment by jech** [comment]
This indicates that the client couldn't establish a video stream to Galene; this is confirmed by the "0+0" which indicates the video and audio throughput.

Are you behind a restrictive firewall?  Can you reach ports UDP/1194 and TCP/1194 on galene.org?

**Comment by jech** [comment]
> udp: 1194 is not accessible.

That's a problem.  You have a firewall somewhere blocking UDP traffic.
