### ISSUE TITLE
File sharing from standard client fails: Obsolete file transfer message downice; please upgrade your client.

### ISSUE THREAD

**Issue by alci63** [jech/galene#223]
Trying to share a file with a user from the web UI fails. It will ask the target user to accept or decline the file sharing, but when accepted the file transfer is cancelled with:

"We have offered to send a file called "myfile.sql" to user franck.

Cancelled: Obsolete file transfer message downice; please upgrade your client."

**Comment by jech** [comment]
The file transfer protocol has changed in an incompatible manner between Galene 1.9.1 and current master.  The error indicates that one of the peers is using the new protocol and the other is still using the old protocol.  Unless you're running behind a reverse proxy, the problem should solve itself on its own after 30 minutes (when the cache entries expire).

If you cannot wait, then please ask both users to click "Shift-reload" on the group page.  If that doesn't fix the issue, ask them to clear their browser caches and then reload.

**Comment by jech** [comment]
Fixed in 1c71a73f8e4693aa1ac1fe50b20a91ff16d4b5c1.  Thanks for the report.
