### ISSUE TITLE
Why use port 1194 for TURN instead of 3478 as assigned by IANA

### ISSUE THREAD

**Issue by alci63** [jech/galene#228]
Officially assigned port to TURN / STUN is 3478 (see https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers for unoffical list).
It is also the port used by Microsoft Teams, so most organisations with allow it.

Why default to 1194, which is assigned to Openvpn, instead of the offical port ?

Nb: of course, the -turn :3478 can be used

**Comment by jech** [comment]
> Why default to 1194, which is assigned to Openvpn, instead of the offical port ?

It's guaranteed to be open in Eduroam networks, see page 32 of the [Edroam Service Definition](https://eduroam.org/wp-content/uploads/2020/02/GN3-12-192_eduroam-policy-service-definition_ver28_26072012.pdf).

Ideally, we should be running TURN and the web server on the same port, but I don't know how to have `net/http` and `pion/turn` share the same port.  I'll file a feature request with Pion.
