### ISSUE TITLE
mise à jour qui c'est mal passée 

### ISSUE THREAD

**Issue by clem-le-lu** [jech/galene#242]
bonjours !
désolé de mettre une issue en français 

bon une mise à jour sur un server yunohost à plantée 

je ne suis pas en recherche de réparer ça pour moi car je ne me servais pas encore de galène (et il n'est pas dit finalement que j'en ai besoin tout de suite ⁽^-^⁾)

je veux juste partager les logs pour vous :blush: 

https://paste.yunohost.org/raw/ahobiveded
https://paste.yunohost.org/raw/tekerivene
https://paste.yunohost.org/raw/izicoqezux

voilà !

bonne journée  o/

**Comment by clem-le-lu** [comment]
alors je me suis trompé .... T-T
ma fourche a langué :sweat_smile: 

donc "une mise à jour de galèe à planté sur mon serveur yunohost" aurais été mieux dit .... :blush:

omme j'ai dit je ne cherche pas une aide je cherche où je peut donner les logs pour le dévelopeurs :innocent: 


> Bonjour,
> 
> Vous êtes au mauvais endroit : pour les mises à jours de Yunohost, il faut demander là : https://forum.yunohost.org/c/apps/11
> 
> Bon courage !

**Comment by jech** [comment]
> comme j'ai dit je ne cherche pas une aide je cherche où je peut donner les logs pour le dévelopeurs 

C'est bien sur forum.yunohost.org que vous les trouverez.  Le développeur de l'intégration de Galène à Yunohost y utilise le pseudo "@ericg".
