### ISSUE TITLE
Galene Server delete all fom "user"

### ISSUE THREAD

**Issue by jjsarton** [jech/galene#245]
If an Operator try to delete all messages from an user, all messages are not deleted.

1) Login as Operator within a group

2) Login as Presenter within the same group within a further Tab
2.1 issue the Message "first message"
2.2 issue the Message "second message"
2.3 issue the Message "third message"

3.1) go to the Operator tab
3.2) double click on one of the message of the presenter

Result: all messages from the presenter are not cleared.
For my test the second message remain displayed

**Comment by jech** [comment]
Fixed in e8b12d3, thanks.
