### ISSUE TITLE
mailing list archive

### ISSUE THREAD

**Issue by Krastanov** [jech/galene#28]
It does not seem the mailing list has a publicly visible archive. The tone of the webpage and hacker news postings imply that the mailing list is the preferred way to contact the developers, but I was hopeful I can read through the archive before asking redundant questions. I tried without and with making an account at https://lists.galene.org/postorius/lists/galene.lists.galene.org/ but the archive did not seem visible anywhere (hopefully I did not miss something obvious).

Any plans to make the archive visible?

**Comment by MisterDA** [comment]
If you go to

    https://lists.galene.org/

You’ll see a link to the archive, at

    https://lists.galene.org/galene/

and the help at

    https://lists.galene.org/galene/_/text/help/

it’s also clonable with

    git clone --mirror https://lists.galene.org/galene

I agree the discoverability of these pages is weird.

-- Antonin
