### ISSUE TITLE
Sanity-checking of settings on startup

### ISSUE THREAD

**Issue by tohojo** [jech/galene#30]
It would be useful if Galene could sanity-check the config on startup. In particular:

- Read all config files and verify their syntax and semantics, log any errors
- Try out the ICE config and log success/failure to connect to each candidate

This would make it easier to be sure that the config works after a change/restart. Maybe even (optionally?) fail to startup if there's an error, so the failure can be picked up by 'systemctl restart'?

**Comment by jech** [comment]
> Read all config files and verify their syntax and semantics, log any errors

We already read all group definitions on startup, see [ReadPublicGroups](https://github.com/jech/galene/blob/master/group/group.go#L823) in group.go.  There are some limitations, though:

  * we silently ignore unknown keys — see [DisallowUnknownKeys](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields);
  * we don't scan subdirectories, only the toplevel directory;
  * we don't warn when we see a file with a name that doesn't end in `.json`.

> Try out the ICE config and log success/failure to connect to each [ICE server]

I'm not quite sure how to do that — creating a PeerConnection is not enough, since you'd actually need to connect to each server to find out if the credentials are correct.  I'll be grateful for advice, ecstatic if it comes with working code.

**Comment by tohojo** [comment]
Juliusz Chroboczek <notifications@github.com> writes:

>> Read all config files and verify their syntax and semantics, log any errors
>
> We already read all group definitions on startup, see
> [ReadPublicGroups](https://github.com/jech/galene/blob/master/group/group.go#L823)
> in group.go. There are some limitations, though:
>
>   * we silently ignore unknown keys — see [DisallowUnknownKeys](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields);
>   * we don't scan subdirectories, only the toplevel directory;
>   * we don't warn when we see a file with a name that doesn't end in `.json`.

Ah, OK. Maybe logging each file read on startup could make this more
visible? Also, for the unkown keys, would it be reasonable to
warn if an unknown field exists, but still allow it (read the file first
with DisallowUnknownKeys set, then if that errors log a warning but
re-read without the flag set)?

>> Try out the ICE config and log success/failure to connect to each [ICE server]
>
> I'm not quite sure how to do that — creating a PeerConnection is not
> enough, since you'd actually need to connect to each server to find
> out if the credentials are correct. I'll be grateful for advice,
> ecstatic if it comes with working code.

I think even just trying one connection to the set of configured servers
would be useful; if it's a credential issue it is likely to fail for all
or none (at least when it's a single coturn instance configured with
multiple listen ports). The errors I ran into was pretty basic user
failure stuff (I messed up the JSON syntax), so just a failure
indication that the ICE config could not be read, or that it was not
possible to establish a peer connection at all, would have been useful :)

**Comment by jech** [comment]
I've just added an undocumented client command `/relay-test` which attempts to connect to itself over a TURN server.  We could potentially do the same on the server side at startup.

**Comment by tohojo** [comment]
Juliusz Chroboczek <notifications@github.com> writes:

> I've just added an undocumented client command `/relay-test` which
> attempts to connect to itself over a TURN server.  We could
> potentially do the same on the server side at startup.

Tried that and it seems to work, thanks! I get this in the Firefox
console: `WebRTC: Using more than two STUN/TURN servers slows down
discovery` - given what you said about Galene not doing TURN-over-TCP
should I Just remove the ?transport=tcp URLs for my TURN server?

**Comment by jech** [comment]
> Tried that and it seems to work, thanks! I get this in the Firefox
> console: `WebRTC: Using more than two STUN/TURN servers slows down
> discovery` - given what you said about Galene not doing TURN-over-TCP
> should I Just remove the ?transport=tcp URLs for my TURN server?

No.  Galène doesn't do direct connections over TCP, it does do TCP TURN.

You may remove the UDP TURN URL, since UDP TURN is of fairly marginal
utility, but if you remove the TCP TURN URL, then you won't be able to
connect over TCP at all.  And that's a lot of networks.

**Comment by tohojo** [comment]
Juliusz Chroboczek <notifications@github.com> writes:

>> Tried that and it seems to work, thanks! I get this in the Firefox
>> console: `WebRTC: Using more than two STUN/TURN servers slows down
>> discovery` - given what you said about Galene not doing TURN-over-TCP
>> should I Just remove the ?transport=tcp URLs for my TURN server?
>
> No.  Galène doesn't do direct connections over TCP, it does do TCP TURN.
>
> You may remove the UDP TURN URL, since UDP TURN is of fairly marginal
> utility, but if you remove the TCP TURN URL, then you won't be able to
> connect over TCP at all.  And that's a lot of networks.

Ah, gotcha! So keeping TCP turn on a port that is highly likely to be
usable on most networks (say, port 443), and maybe combining that with a
UDP port that is more likely to be open than the high port range used by
Galene by default? Say, port 500, or 1194 or something like that? Any
recommendations?

**Comment by jech** [comment]
> Ah, gotcha! So keeping TCP turn on a port that is highly likely to be
> usable on most networks (say, port 443), and maybe combining that with a
> UDP port that is more likely to be open than the high port range used by
> Galene by default? Say, port 500, or 1194 or something like that? Any
> recommendations?

500 (IKE), 1194 (OpenVPN), 4500 (IPsec NAT traversal), 10000 (Cisco VPN).

**Comment by jech** [comment]
> we silently ignore unknown keys — see DisallowUnknownKeys;
> we don't scan subdirectories, only the toplevel directory;
> we don't warn when we see a file with a name that doesn't end in .json.

Fixed in 61990ff1efb15a9f9facfa2dad16b6efe9ba890a and 98235afe06ff58f56b6a2c0380637d44fca9617a.

**Comment by jech** [comment]
The remaining bit is fixed in 25ce8ef6661155231edaa17d5f1a132e7df29321.

**Comment by tohojo** [comment]
Juliusz Chroboczek <notifications@github.com> writes:

> The remaining bit is fixed in
> 25ce8ef6661155231edaa17d5f1a132e7df29321.

Yup, works, thanks!

Jan 14 10:28:43 video systemd[1]: Started Galene server.
Jan 14 10:28:43 video galene[673981]: 2021/01/14 10:28:43 2021-01-14 10:28:43.288874555 +0000 UTC
Jan 14 10:28:43 video galene[673981]: 2021/01/14 10:28:43 2021-01-14 10:28:43.289303742 +0000 UTC m=+0.046142445
Jan 14 10:28:43 video galene[673981]: 2021/01/14 10:28:43 Relay test successful in 41.036085ms, RTT = 447.848µs

I assume those two timestamps are output by the relay test? Might be
useful to explain what they are?

**Comment by jech** [comment]
They're left-over debugging messages.  I've removed them.

**Comment by tohojo** [comment]
Juliusz Chroboczek <notifications@github.com> writes:

> They're left-over debugging messages.  I've removed them.

Yup, that's better - thanks! :)
