### ISSUE TITLE
Systemd service file in the repository ?

### ISSUE THREAD

**Issue by rgrunbla** [jech/galene#38]
Hi,
thank you for the software. I'm currently packaging galene for NixOS, and I'd like to know if you could put an example systemd service file directly in this repository to avoid shipping some "custom" one in the downstream package.

Thanks,
Rémy

**Comment by MisterDA** [comment]
There is an example systemd service file in the readme. I've written a complete integration with systemd (service, sysusers, tmpfiles) for the [Arch Linux package](https://aur.archlinux.org/cgit/aur.git/tree/?h=galene).

**Comment by rgrunbla** [comment]
Yeah, it's in the readme, but it means I have to reproduce the code in the downstream package, whereas I could just use the file directly. Sorry if I was not clear enough.

**Comment by jech** [comment]
No, sorry, I don't with to encourage people to use systemd.
