### ISSUE TITLE
Command line flags for the certificates and private key ?

### ISSUE THREAD

**Issue by rgrunbla** [jech/galene#39]
Hi,

I think it would be nice to be able to customize the location of the certificates used by galene directly with flags on the command line, e.g. ```-cert /etc/galene/certificate.pem``` and ```-key /etc/galene/key.pem```, instead of forcing them to have specific name and be in the data directory. Part of why I want this is to be able to integrate more nicely with my NixOS package attempt for galene ( https://github.com/NixOS/nixpkgs/pull/109414 ). What do you think ?

Thanks,
Rémy

**Comment by jech** [comment]
I have no strong objection, but why can't you symlink the keys into the data directory?

**Comment by jech** [comment]
Closing due to lack of feedback.  Symbolic links solve the problem, no need to simulate a filesystem inside Galène.
