### ISSUE TITLE
Optional use of coturn's volatil authentication

### ISSUE THREAD

**Issue by athoune** [jech/galene#40]
With hard coded Coturn account, you can reuse the TURN service, even if your application account is revoked.

Coturn can use a simple hmac password with timestamp and a sercret salt :
https://github.com/coturn/coturn/blob/060bf187879fd1a6386012f4c5a7494824ebe5c8/README.turnserver#L180-L193

With that, galene can compute a coturn account, usable for few hours, for every user, without creating explicit account on coturn side.

**Comment by jech** [comment]
This is implemented, and described here: https://github.com/jech/galene/blob/master/README#L79 .
