### ISSUE TITLE
Use go module versions for release tags

### ISSUE THREAD

**Issue by jfkw** [jech/galene#41]
Thanks for releasing galene. I am working on community galene packaging for openSUSE and it would help with certain packaging automation steps if the release tags used [go module versions](https://golang.org/ref/mod#versions) e.g. `v0.1.0` and `v0.2.0`.  Would you consider adopting this convention?

I think it would work to add tags `v0.1.0` and `v0.2.0` at the same revisions as `galene-0.1` and `galene-0.2` and continue the future release sequence from there. This method works locally:

```
$ git for-each-ref refs/tags
4dc254d7822fcf5eb016a0152e773f83721adb74 tag    refs/tags/galene-0.1
5f7455af5bf78c837008e80fe4b67809badce3c0 tag    refs/tags/galene-0.2

$ git tag -a -m 'v0.1.0' v0.1.0 4dc254^{}
$ git tag -a -m 'v0.2.0' v0.2.0 5f7455^{}

$ git for-each-ref refs/tags
4dc254d7822fcf5eb016a0152e773f83721adb74 tag    refs/tags/galene-0.1
5f7455af5bf78c837008e80fe4b67809badce3c0 tag    refs/tags/galene-0.2
533ce3fe8b1cc735c700d6e4bc773a9a1ab0fe7a tag    refs/tags/v0.1.0
a9747d99ac7c38217433a647f7f0e4cdc2965aad tag    refs/tags/v0.2.0
```

**Comment by jech** [comment]
This is deliberate: Go module versions have semver semantics, while Galène's user-visible version number doesn't.

I'm not sure what to do about this, but apparently using a development process incompatible with semver is not supported by the Go module tools.

**Comment by jech** [comment]
Closing due to lack of feedback.
