### ISSUE TITLE
Rename file LICENSE from LICENCE

### ISSUE THREAD

**Issue by jfkw** [jech/galene#42]
The file `LICENSE` is currently misspelled `LICENCE`. Renaming the file will help detection in GitHub and distribution packaging (I am working on packaging for openSUSE).

**Comment by MisterDA** [comment]
It's the valid british spelling. Your tools should be updated to support all forms of english ;-)

**Comment by jfkw** [comment]
So it is, apologies for overlooking that. No worries, it's simply another spelling of input to an RPM macro and will work as is.
