### ISSUE TITLE
running Galene behind haproxy ?

### ISSUE THREAD

**Issue by nlienard** [jech/galene#45]
Question is about HAPROXY.

Galene is installed sucessfuly but can't see each other on a room. 

I only see my own face. (users also see only their own face).

Configuration
   Running Galene in a container with only a private IP ( 192.168.10.111)
   Public IP is behind another container dedicated to haproxy  (192.168.10.252 + PUblic IP ) which send the 443 traffic to Galene container on 8443 port.
   Also some iptables redirect for 1194/UDP and 10000-65535 udp port from Haproxy container to Galene container.

when starting Galene:

```
# ./galene -turn PUBLIC_IP:1194
2021/01/22 11:51:01 Starting built-in TURN server
2021/01/22 11:51:21 Relay test failed: timeout
2021/01/22 11:51:21 Perhaps you didn't configure a TURN server?
2021/01/22 11:53:31 client: read tcp 192.168.10.111:8443->192.168.10.252:35850: read: connection reset by peer
```

As we can see, it shows Haproxy IP (192.168.10.252) instead of user IP. (X Forward For ?).

Does Galene support haproxy ?

thanks

**Comment by jech** [comment]
It looks like haproxy is breaking the WebSocket connection (that's what the "client:...connection reset by peer" message implies).  Please check the haproxy documentation, and make sure that haproxy is configured in order to proxy WebSocket connections to `/ws` with a timeout of at least 60 seconds (and preferably more, since Galène will timeout idle WebSocket connections on its own).
Please summarise your configuration here once you get it working.

**Comment by nlienard** [comment]
Finally i set directly a public IP and it works.
but with a phone, i got wss error. 
Anything to do for mobile support ?

**Comment by jech** [comment]
> Anything to do for mobile support ?

Are you using a TLS certificate that's signed by an authority recognised by the mobile?

**Comment by nlienard** [comment]
Finally, it works on mobile. I'm using LET'sENCRYPT certif but i was migrating DNS to the dedicated IP i put on the container.
In the meantime of DNS propagation, i was testing directly with public IP  https://IP and indeed it was due to certificate SSL not matching. 

When DNS was ok, all became good ! Thanks !

**Comment by nlienard** [comment]
For haproxy, if you have some clue about the configuration, i would be interested because i would prefer to have Galene behind it. Any way, great works, it is so simple to setup compared to BBB (i tried it just before and it was just insane).

**Comment by jech** [comment]
Glad you've solved your immediate problem.  Please do summarise your findings when you manage to get Galène to work behind haproxy.

**Comment by nlienard** [comment]
I did some new test with haproxy, for now it looks like to work but it autodisconnects use when idling.

On frontend, i added:

        # Galene START OPTIONS
        timeout connect 0ms
        timeout client 0ms
        timeout server 0ms
        option  http-server-close
        # Galene END OPTIONS

Still using "mode http" because this frontend is shared with many other services but i guess it would be better to have "mode tcp" for websocket.

**Comment by jech** [comment]
> I did some new test with haproxy, for now it looks like to work but it
> autodisconnects use when idling.

Galène sends a keepalive every 45 to 55 seconds.  Please make sure all of
your timeouts are set at 60s or more.  Perhaps you need to set the
http-client or http-keep-alive timeouts?

(Aside.  TCP is a connected protocol, and unless there's something very
wrong with the implementation of the proxy, there should be no problem
using timeouts on the order of hours or even days.)

**Comment by nlienard** [comment]
I put 90 sec the timeout but still these errors when a user is disconnected abrubtaly: 

Jan 26 09:26:30 atxovh-vis500 galene[16489]: 2021/01/26 09:26:30 PushConn: client is dead
Jan 26 09:26:30 atxovh-vis500 galene[16489]: 2021/01/26 09:26:30 client: read tcp 192.168.10.112:443->192.168.10.252:34536: read: connection reset by peer

**Comment by nlienard** [comment]
![image](https://user-images.githubusercontent.com/13884545/105828686-b7180c00-5fc3-11eb-866d-033731d73a51.png)

This is the message in browser when it kicked me out.

**Comment by nlienard** [comment]
I was focus in modification on FRONTEND timeout but it appears there are also timeout in BACKEND side.
After overriding the default, it looks like it is not disconnecting anymore.

in Backend:

  timeout connect       600s
  timeout server        600s

**Comment by nlienard** [comment]
Now haproxy is working, i turned-off the STUN server json to use only the internal one but not working:

 ```
Jan 26 12:25:42 atxovh-vis500 galene[18949]: 2021/01/26 12:25:42 Relay test failed: timeout
Jan 26 12:25:42 atxovh-vis500 galene[18949]: 2021/01/26 12:25:42 Perhaps you didn't configure a TURN server?
```

On haproxy container, i got iptables to redirect port 1195 to the Galene container. (TCP/UDP).

**Comment by nlienard** [comment]
Ok i had an asymetrical routage, now it works !!!

**Comment by jech** [comment]
> On haproxy container, i got iptables to redirect port 1195 to the Galene
> container. (TCP/UDP).

Does your firewall implement hairpinning?

**Comment by nlienard** [comment]
it was the default gateway of the Galene container which was using another public ip (HAPROXY container has multiples IP public).
Now, that the network configuration is proper, all is working FINE !

**Comment by jech** [comment]
I'm glad to hear that.

**Comment by nlienard** [comment]
I 've still some error like that : 

```
Jan 26 14:16:28 atxovh-vis001 galene[558]: turn ERROR: 2021/01/26 14:16:28 error when handling datagram: failed to handle Allocate-request from 82.64.236.146:42213: relay alr
for 5-TUPLE
Jan 26 14:16:29 atxovh-vis001 galene[558]: turn ERROR: 2021/01/26 14:16:29 error when handling datagram: failed to handle Allocate-request from 82.64.236.146:42213: relay alr
for 5-TUPLE
Jan 26 14:16:30 atxovh-vis001 galene[558]: turn ERROR: 2021/01/26 14:16:30 error when handling datagram: failed to handle Allocate-request from 82.64.236.146:42213: relay alr
for 5-TUPLE
Jan 26 14:16:30 atxovh-vis001 galene[558]: turn ERROR: 2021/01/26 14:16:30 error when handling datagram: failed to handle Allocate-request from 82.64.236.146:40939: relay alr
for 5-TUPLE
Jan 26 14:16:30 atxovh-vis001 galene[558]: turn ERROR: 2021/01/26 14:16:30 error when handling datagram: failed to handle Allocate-request from 82.64.236.146:44369: relay alr
for 5-TUPLE
```

Could it be due to the fact i'm using 2 devices under my wifi network ?

thanks

**Comment by jech** [comment]
This is probably nothing to worry about.  Please see https://github.com/pion/turn/issues/197.
