### ISSUE TITLE
Creating new room without editing json

### ISSUE THREAD

**Issue by nlienard** [jech/galene#48]
Hello

Thanks/Merci for this amazing application, it works very fine.

I've some users who wants to create dynamically a room without registering it through json edition. (it is not user-friendly ^^).

What is the best way ? to create a default public room named "private" and allowing subgroups then the users have to add their room in the URL ? 

Do you think it would be possible for future to allow users to create a new room through the root page ? (and to protect the room by a secret/password).

thanks again !

**Comment by jech** [comment]
For now, allowing subgroups is the only way.

We certainly need an administrative interface that allows people to create new groups, let's please dicuss it at https://github.com/jech/galene/issues/11.
