### ISSUE TITLE
docker-compose config

### ISSUE THREAD

**Issue by jvanveen** [jech/galene#5]
I was wondering whether you would consider a contribution of a docker-compose config for nginx/coturn and possibly galene itself. Do you think it may be useful for people who want to give Galene a quick try?

**Comment by jech** [comment]
I think it would be useful to send it to the mailing list (https://lists.galene.org/postorius/lists/galene.lists.galene.org/).  I won't include it in Galène itself, since I don't use Docker and therefore won't be able to maintain your contribution.

**Comment by jvanveen** [comment]
I'll do! Thanks for the reply
