### ISSUE TITLE
A bug that may become a feature (Test your video)

### ISSUE THREAD

**Issue by castagnag** [jech/galene#50]
I consistently noticed the following behavior:

1. Open a group page
2. Connect to the group
3. go into "Panic" mode, so that the "Ready" button is visible (either because you connected with autoready disabled or because you pushed "Panic")
4. Log out with the "Ready" button visible

What happens is that the "Ready" button does not disappear, even if you are no longer connected (see attached screenshot at the end)

But what is _really_ interesting is that you can press the "Ready" button and the image appears. So this is a way to test your webcam without being connected. 

If you press "Panic" when you are disconnected, then the "Ready" button no longer appears so you are back at point 1.

This suggests a feature. That is, if when you are disconnected the "Ready" button becomes a "Test video" button, and it is always on the connection page (that is, already at step 1) then you have a way to ... Test your video of course. The only modification that would be necessary is to have also the webcam selection menu in the setting part even when you are not connected (currently I just have the "Other settings" part)

![20-11-09 13-03-38 0177](https://user-images.githubusercontent.com/1931805/106134350-b23f8d80-6166-11eb-8e04-6f952a68c4a6.png)

**Comment by jech** [comment]
Fixed in fe9b892.

**Comment by jech** [comment]
As to testing the camery, we should implement an « echo test », where you see both the video captured by your camera and the video echoed by the server.  This would allow testing your network connection in addition to the webcam.
