### ISSUE TITLE
The group is locked

### ISSUE THREAD

**Issue by Djiko** [jech/galene#57]
Hi all, 

I'm certainly doing something wrong but I don't manage to create a working group, even a very simple one, copying the default public group configuration. What happens is that the Op can log in, but nobody can join the group as the server seems to kick them : the group is locked.

The most simple configuration I tried is the following one, without further success:

```
{
    "op": [{"username": "OP_USER", "password": "OP_PASSWORD"}],
    "presenter": [{}]
}
```

I tried the various option of the documentation. I even tried to copy the public group's config in a new file. Even then I'm locked out of the group as a simple user.

What am I doing wrong?

Thanks.

**Comment by jech** [comment]
You probably typed `/lock` in the group.  You may unlock it by typing `unlock`.

Once locked, a group will remain locked until you either unlock it or restart the server.

**Comment by Djiko** [comment]
Indeed, it was as simple as that. Thanks a lot.
