### ISSUE TITLE
tls: no cipher suite supported by both client and server

### ISSUE THREAD

**Issue by mankins** [jech/galene#60]
Hi. I have a server setup and am proxying behind nginx.

I start the server with:

```
 ./galene --turn public.ip.address.here
```

And am seeing a bunch of errors printed to `stdout`:

```
tls: client offered only unsupported versions: [300]
tls: no cipher suite supported by both client and server
error when handling datagram: failed to handle Allocate-request from 73.38.140.198:57891: relay already allocated for 5-TUPLE
turn ERROR: 2021/03/17 19:52:30 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header
```

```
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 03:25:49 ICE: unknown id in ICE
2021/03/17 20:43:25 Relay test successful in 31.700699ms, RTT = 223.554µs
```

Should I be concerned about these?

**Comment by jech** [comment]
> tls: client offered only unsupported versions: [300]

This looks like a non-TLS client attempting to connect.  I wouldn't worry.

> error when handling datagram: failed to handle Allocate-request from 73.38.140.198:57891: relay already allocated for 5-TUPLE

Yes, there are some issues with the built-in TURN server (see for example https://github.com/pion/turn/issues/206 or https://github.com/pion/turn/issues/144).  Probably nothing to worry about, Galène should recover within 30s from failed TURN connections, but something that needs fixing at some point.

> turn ERROR: 2021/03/17 19:52:30 error when handling datagram: failed to create stun message from packet: unexpected EOF: not enough bytes to read header

That probably means that somebody sent an empty packet to your TURN server.  Probably nothing to worry about.

> 2021/03/17 03:25:49 ICE: unknown id in ICE

That means that a connection was closed before it was fully negotiated (for example, a user clicked *Ready* and then immediately clicked *Panic*).  The server is receiving negotiation messages for a connection that no longer exists.  I should probably detect this case and do something about it, not sure how to do that, though.
