### ISSUE TITLE
Monitoring (Prometheus or JSON)

### ISSUE THREAD

**Issue by erdnaxe** [jech/galene#62]
Galène already has `/stats` for some private room statistics. It would be great to add a Prometheus-formatted `/metrics` HTTP endpoint that also exposes some useful metrics about the instance.

I believe we want `/metrics` to show only anonymous data such as total number of users (only public rooms ?) and total number of WebRTC session exchanged. These metrics can then be pulled by a Prometheus server or other monitoring services.

I already implemented something similar here : <https://github.com/erdnaxe/ghostream/blob/dev/internal/monitoring/monitoring.go>. If you are positive about adding such feature, I would enjoy writing a pull request for Galène.

Best regards,

**Comment by jech** [comment]
Quite frankly, I'm not sure.  On the one hand I understand that people want to use the tools they're familiar with, on the other hand I'm not too keen on introducing additional dependencies, I'd like to read the code of the Prometheus Go library first.

See also #23.

**Comment by erdnaxe** [comment]
I looked at the closed pull request, and I agree that we don't want to add useless complexity/external dependencies.

Maybe Galène could either:

- Make `/stats` more easy to parse. This would enable people to write their own "gateway" exporters for their specific monitoring system. This is what is being done with NGINX (https://github.com/nginxinc/nginx-prometheus-exporter).

- Add a `/stats.json` that is basically `/stats` but in JSON format. Same effect as previous idea, but it makes parsing more easy.

- Add a `/metrics` in Prometheus format (which is basically a text file with one metric per line annotated with labels). This can either be home-made or by using a external dependency.

I like the 2nd approach because then Galène does not promote one monitoring system other another.

If Galène can be monitored, then people might want to add more metrics such as some load-related metrics, number of users using the service and number of active streams.

**Comment by jech** [comment]
I am very open to making a `stats.json` — Galène already uses JSON, so this introduces no new dependency.  In order to avoid duplication, we should probably rework `stats` to be a piece of JavaScript that fetches `stats.json` and formats it in a friendly manner.

I know nothing whatsoever with Prometheus.  I'd be grateful if a proponent of Prometheus could educate me.

**Comment by erdnaxe** [comment]
> I know nothing whatsoever with Prometheus. I'd be grateful if a proponent of Prometheus could educate me.

Prometheus is a time-series database. To compare its properties with a classical SQL server (PostgreSQL/MySQL):

 * Rather than inserting rows in tables, you can only insert data points in the end of series which make it space-efficient, but also very frustrating when you want to merge multiple databases/history.
 * Rather than querying data with SQL, you query using PromQL which enables people to get the derivative/integrate of time series, do linear regressions... It's yet-another syntax but some tools exist to help and to plot the results (such as Grafana).
 * Prometheus can be configured to periodically pull the content from some http/https pages. What people are calling "exporters" are just web servers serving text that Prometheus can understand.
 * It's written in Golang, and I believe it's using the Golang standard library to do all the HTTP part.
 * Prometheus is young (packaged in Debian since Stretch) but seems quite popular recently.

Going back to Galène, this means that if a `/stats.json` is created, then people will be able to write a small web server ("exporter") that will be able to fetch this JSON and format it for Prometheus. But actually if they are using Icinga/Munin/something else, they can also write a script to inject this JSON to these other monitoring systems.

**Comment by jech** [comment]
In current master, `/stats` has been replaced with `/stats.json`.
