### ISSUE TITLE
"You are not allowed to record"

### ISSUE THREAD

**Issue by gregfr** [jech/galene#63]
Thanks for this amazing software!

I'm trying to test the record feature, but I keep having the error message "You are not allowed to record". I'm the op of the group, and I've added this to the group config:
`"allow-recording": "true"`

What am I doing wrong?

Thanks in advance

Regards

**Comment by jech** [comment]
Are you logged in as an operator?  In order to record, you need both the following conditions to be satisfied:
  * allow-recording must be true;
  * the user who types "/record" must be logged in as an operator.

**Comment by jech** [comment]
No, there's no proper logging infrastructure yet.

Can you please go to the Javascript console, and type
```
serverConnection.permissions;
```

**Comment by jech** [comment]
> "allow-recording": "true"

Sorry, I've only just noticed — this should say

> "allow-recording": true

without quotes around `true`.  In the last version of Galène (0.3.2), this typo leads to the following error:

> Group file groups/public.json: json: cannot unmarshal string into Go struct field description.allow-recording of type bool

**Comment by gregfr** [comment]
You spotted it, thanks!
