### ISSUE TITLE
Retrieve permission statuses of other users

### ISSUE THREAD

**Issue by jvanveen** [jech/galene#64]
I'm currently working on the context menu of Pyrite(https://github.com/garage44/pyrite/issues/15). To be able 
to show the right options, I need to be able to tell what permissions other users have. I'll try to make a PR 
out of it.

**Comment by jech** [comment]
Agreed.  This is also needed for mainline Galène (the coloured blobs should reflect operator status).

I think we should extend the "user" message to carry permissions.  Make sure a "user" message of kind "change" is sent when a user's permissions change.

**Comment by jech** [comment]
https://lists.galene.org/galene/87pmzpydxm.wl-jch@irif.fr/

**Comment by jvanveen** [comment]
Sounds good! I like the idea of a state object for custom actions like hand raised. Could probably be used as well to indicate a user's muted state then.

**Comment by jvanveen** [comment]
I made a draft context menu for users and group using two kebab menus. Not really sure if I identified all features correctly; just something to get started. Running at https://beta.pyrite.video/groups/pyrite (pyrite/1234). Probably needs some more work. Also, it got me thinking that some room-related state may be useful to have as well. E.g. the items in the room context mostly would have an 'on' or 'off' state.

**Comment by jech** [comment]
This was implemented in f0a39fca48e84af3f6332e9f2cb2144fbc9cb7b3 and 3ba2394be7819babdf1c104fa2bcf90ecffbf357.  There is now a dictionary `serverConnection.users` that contains usernames, permissions and statuses.  There is a new userAction called `setstatus` that sets a user's status; for now, a user can only set their own status, I'll add the ability for admins to set other users' status if there is demand.

Statuses are not interpreted by the server, so you may use any names you wish.  It would be good if we could coordinate on a common set of statuses, to avoid confusion, and perhaps allow our clients to interoperate.
