### ISSUE TITLE
Ability to retrieve streams url

### ISSUE THREAD

**Issue by roipoussiere** [jech/galene#69]
It could be useful to independently get video and audio inputs of the room participants in order to use them in other softwares that can read video streams by url (such as [VLC](https://www.videolan.org/vlc/)), and allow developers to create tools that work with Galene without having to modify Galene source code.

**Comment by fabricerouillier** [comment]
It would also allow to stream ..... which much be a solution for attendees with a slow connexion (stream on a server equipped with a web page and a chat)

**Comment by jech** [comment]
The set of streams varies dynamically as people join and leave the conference.  What streaming protocol do you envision that can handle dynamically varying sets of streams?

**Comment by jech** [comment]
Closing due to lack of good ideas.
