### ISSUE TITLE
Request : change default TURN port so it doesn't collide with OpenVPN

### ISSUE THREAD

**Issue by la-balisa** [jech/galene#72]
Port 1194 is the default for OpenVPN (https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), and i (and many people) use it a lot.
With all the ports available, could we choose another one to be the default ?
I suggest 8444, as it is only non-officially registered on TCP by Bitmessage, and it's UDP in our case, and it's next to 8443, but any free port would do the trick.

**Comment by jech** [comment]
This is deliberate — the OpenVPN port is guaranteed to be open in Eduroam networks, and a lot of our users use Eduroam.  You'll need to tweak your configuration if you're running OpenVPN on the same host.  Sorry for that.
