### ISSUE TITLE
Formating the README to a README.md to have anchors, links etc

### ISSUE THREAD

**Issue by Naereen** [jech/galene#73]
Hello there,
I just discovered your awesome project! It's very impressive!

I have one tiny suggestion: by renaming the README file to a README.md file (and maybe checking or fixing some markup, but I think it won't be needed), GitHub homepage (https://github.com/jech/galene/) will be able to display the links, put anchors on the titles, generate a table of contents, etc.

Thanks, and regards from :fr: Rennes! -- @Naereen

**Comment by MisterDA** [comment]
Multiples PR were opened to propose this change, but the maintainer opposes it and has his reasons. I doubt that this would be changed anytime soon, unless GitHub starts rendering LaTeX on the fly ;-)

**Comment by Naereen** [comment]
Oh, sorry, I didn't check the previous PR.
I don't find reasons but there might be, alright!

By the way, using GitHub actions like <https://github.com/pandoc/pandoc-action-example> or <https://www.r-bloggers.com/2020/03/github-actions-for-compiling-and-converting-latex-2/> it should very quick to set-up an automated process of keeping a live README.md from a set of LaTeX sources, but I won't have time to do that in a PR for you, sorry!

**Comment by Naereen** [comment]
So just to be sure, @jech you're opposed to this suggestion, and too busy to say hi or thank you or anything?
It's alright, no offense taken, but it's a surprisingly cold way of communicating here on GitHub.

**Comment by Naereen** [comment]
If you have time, could I ask what are your arguments against having the links and titles and anchors correctly displayed here in GitHub?
If it's already explained somewhere in another ticket, could someone please give me the link?
Thanks!

**Comment by jech** [comment]
Sorry if I seemed cold, that was not my intention.  @MisterDA adequately answered your report, and I'm trying to avoid excessive noise on the bug tracker (which is for tracking bugs).  The <galene@lists.galene.org> mailing list is a better forum for general discussion.

> If you have time, could I ask what are your arguments against having the links and titles and anchors correctly displayed here in GitHub?

* https://github.com/jech/galene/pull/3#issuecomment-749657999
* https://github.com/jech/galene/pull/3#issuecomment-750413092

**Comment by Naereen** [comment]
Alright, thanks a lot @jech for the detailed explanation!

I'm extra interested to join this mailing list, as I'm now a big fan of Galene! How can I subscribe please? (I can't find any documentation! If you can add `my pseudo` à `crans` dooot `O R G`, thanks!

**Comment by jech** [comment]
Please go to

  https://lists.galene.org

and choose the second link.
