### ISSUE TITLE
Firefox+IPV4+NAT

### ISSUE THREAD

**Issue by fabricerouillier** [jech/galene#74]
Hi

Thanks a lot for this project, Galène is working like a charm and is so simple to install / customize / use.

I have detected one problem which happens in a very specific situation : 

Client : **IPV4** network (no IPV6) and some latency (4G) - **Firefox navigator**

Server : **behind a NAT** (Freebox) and a **reverse proxy** (Traefik) launched with the command : 

  ` /home/galene/galene -insecure -turn EXTERNAL_IP:1194`
   
Works like a charm excepted with a client IPV4 only running firefox.
   
In order to reproduce  this, it is sufficient to deactivate the IPV6 on the galene server.

[EDIT] 
- the /relay-test command on the client side drives to an Error (timeout) which tends to prove that the turn is not working properly
- the "Relay test" on the server siide is successfull

**Comment by jech** [comment]
The discussion has moved to https://lists.galene.org/galene/87v98uz0fv.wl-jch@irif.fr/T/
