### ISSUE TITLE
Saving to disk is fragile

### ISSUE THREAD

**Issue by jech** [jech/galene#8]
The code that writes a video to disk (diskwriter.go) has a number of limitations:
 * it does not react correctly to persistent packet loss (both a packet and its resent copy being lost), which occasionally causes corruption;
 * it loses a small number of frames at the end of a video;
 * it does not properly terminate the container file, which is not seekable unless it is postprocessed.
 
Fixing this will require changes to both the samplebuilder and webm libraries that the disk writer uses.

**Comment by deleolajide** [comment]
It also does not work with Windows compiled binary. The recorder folder is created, but no files are created. If galene binary is run from Windows Subsystem for Linux (WSL2), then the files get created.

**Comment by jech** [comment]
Hmm... Windows probably doesn't like the format we're using for the filename.  So it's actually two bugs here:
  * logging is deficient; and
  * the filename used is not portable to Windows.
  *

**Comment by deleolajide** [comment]
> (Side note — I've never tested Galène under Windows, I'm actually surprised it works in the first place.)

It works brilliant. Apart from no logging and missing recorded files, everything else seems to work OK.  Thank you for releasing it as open source and giving us all a chance to contribute to your excellent work 👍

**Comment by jech** [comment]
The Windows issue should be fixed in 159a9b8147376fa8c4e70be4b4c6ba22c0e49c6a.  @deleolajide, please confirm.

I've added some feedback in 6969ae7d68e0dcc18a07a47ed916d7828893cb5b.

**Comment by deleolajide** [comment]
I can happily confirm Windows recording issue is fixed. Thanks 👍 

![image](https://user-images.githubusercontent.com/110731/103084455-ec04fd80-45d6-11eb-8492-273bc4817450.png)

**Comment by jech** [comment]
Fixed in e840e53ac2695ca5c6d7973cc574c2663675a0ad, b0c39fca22287010661de201386eb92ff14d0701, bcd62f190b8390517056a28251e889bd7a12deaf.
