### ISSUE TITLE
CSS for .media-failed is not visible enough

### ISSUE THREAD

**Issue by jech** [jech/galene#87]
When a stream is not working, the video element gets CSS class `.media-failed`.  This happens before Galène has established the flow, it happens if the flow cannot be established, and it happens if the flow fails and Galène has to renegotiate.  As indicated by #86, the appearance of `.media-failed` is not visible enough.  Unfortunately, it cannot be made into a big red warning, since it happens at the beginning of every connection — it can take up to two seconds to establish a flow if we go over TURN.

Somebody with taste has to come and redesign the `.media-failed` class to be visible and comprehensible to the user, even in the case where there's no video, and simultaneously unobtrusive enough so that the flash of `.media-failed` at the beginning of the connection is not distracting.

**Comment by erdnaxe** [comment]
> redesign the .media-failed class to be visible and comprehensible to the user, even in the case where there's no video, and simultaneously unobtrusive enough so that the flash of .media-failed at the beginning of the connection is not distracting.

What about going with a spinner animation (such as <https://projects.lukehaas.me/css-loaders/>)? I may try design one using only CSS if it's what we want.

**Comment by jech** [comment]
> What about going with a spinner animation

We could try, but I think that spinner animations irritate people.  I'm
looking for something softer.

**Comment by jech** [comment]
Fixed in b91d48d.  An animation would still be welcome.
