### ISSUE TITLE
Sound streams in recordings

### ISSUE THREAD

**Issue by stevenmache** [jech/galene#91]
Hi, thanks for galene, it's great !
I like to record the meeting of galene, for instance a screen share with my webcam in a corner.
Problem is that the recording create 1 stream per video canal. In this example 1 for my webcan + 1 for the screen sharing.
The sound of my voice is on the stream of the webcam but not on the one recording the screen share. 
What would be usefull is to have all the audio streams mixed for the sharing screen / windows recordings.
It would also be usefull to have 1 recording regrouping all videos + all audios.

**Comment by jech** [comment]
Unfortunately, there is no widely deployed container format that allows varying the number of video and audio tracks dynamically, so what you're asking is impossible to do (without recoding the video, which Galène doesn't do).  See also #10.
