### ISSUE TITLE
Can't activate microphone on iPhone

### ISSUE THREAD

**Issue by gregfr** [jech/galene#95]
Greetings
I'm happily using Galene with a lot of people and they all love it, but (for some obscure reason) some of them are still using iPhones, and they are reporting they cannot join because they cannot activate the microphone, even if they click "Allow". Do you know a way to work around that?
I'm using Galene on server with a public name and a certificate from Let's Encrypt.
Thanks in advance
Regards

**Comment by jech** [comment]
Please ask them to check that *both* of the following are true:

   * their web browser (Safari?) is allowed to use the microphone (Settings->Safari->Camera);
   * the website is allowed to access the microphone (Safari->Preferences->Websites).

**Comment by jech** [comment]
Closed due to lack of response.

**Comment by gregfr** [comment]
Sorry for the delay. I'll contact someone with an iPhone and do some testing.

**Comment by gregfr** [comment]
I asked a friend with an iPhone, he as the error: `NotReadableError: The I/O operation failed`.
He has none of the menus you mentionned...
iOS 14.7.1

**Comment by gregfr** [comment]
I also tested on BrowserStack, most iPhones are working, but iPhone XS 12.1 gives "The server said; negociation failed"... iPhones are weird...

**Comment by jech** [comment]
Is that with Galene 0.4 or 0.3?

**Comment by jech** [comment]
Weird platform issue, probably not a bug in Galene.  Please reopen if this turns out to be specific to Galene.
