### ISSUE TITLE
How Pause/Play video incoming videostream?

### ISSUE THREAD

**Issue by shalom-aviv** [jech/galene#96]
Hi

Can client pause/play video stream for particular user?

For example 
30 users in a conference and always talks from 3 to 5. 
When user silent we pause his video stream and shows avatar, when user become active we play his video stream.
Audio stream always active for all users.

Does it possible in your solution? 
If not could you please give helpful advice, how I can implement this feature?

Thank you!

**Comment by jech** [comment]
The user can disable the stream by clicking *Panic*, or they can disable just the video track by selecting *Camera: none* in the side menu.  The group administrator can disable a user's video by doing */unpresent user* in the chat.

Other scenarios should be easy to implement, but you'll need to precisely specify what you need.

**Comment by shalom-aviv** [comment]
Thanks for your fast response!

My question about client side

- 10 users in conference
- I see all 10 video streams in browser window
- I want see video streams only for 5 particular users and i'm not an admin
- I want have possibility at any moment on/off video stream for any user in current conference
- any action affect only my browser client

Sorry if I'm not clear

**Comment by jech** [comment]
Ah, I see.

In Galène 0.3, this is not possible — you receive either all video streams or none.  In the current master branch, it is possible to disable the video stream by using the `Stream.request` method:
```
  c.request(['audio']);
```
This is used in the `reconsiderDownRate` function in `galene.js`, where we decide, depending on the size of a video, whether to request the full-quality video or just a low-quality thumbnain.

**Comment by shalom-aviv** [comment]
See!
Thanks
