### ISSUE TITLE
UI element for stopping screen sharing should have better visibility

### ISSUE THREAD

**Issue by stroeder** [jech/galene#98]
Currently a white close-cross is shown on transparent background for stopping a certain shared screen.

This is very hard to perceive if the shared screen content is bright, even if the user searches for it. Also it's very small and might be hard to push on touch screens.

Suggestion: At least use a dark background and make it a little bigger.

**Comment by jech** [comment]
@takdj ?

**Comment by jech** [comment]
Fixed in d29f6d6.

**Comment by takdj** [comment]
d29f6d6 is a good fix I my opinion. I've added a text shadow for top controls but it seems it was not enough.
